<?php
/**
 * Language labels for plugin SpellChecker of htmlArea RTE (extension: rtehtmlarea)
 * 
 * This file is detected by the translation tool.
 */

$LOCAL_LANG = Array (
	'default' => Array (
		'Spell Checker' => 'Spell Checker',
		'CONFIRM_LINK_CLICK' => 'Please confirm that you want to open this link',
		'Cancel' => 'Cancel',
		'Dictionary' => 'Dictionary',
		'Finished list of mispelled words' => 'Finished list of mispelled words',
		'I will open it in a new page.' => 'I will open it in a new page.',
		'Ignore all' => 'Ignore all',
		'Ignore' => 'Ignore',
		'NO_ERRORS' => 'No mispelled words found with the selected dictionary.',
		'NO_ERRORS_CLOSING' => 'Spell check complete, didn\'t find any mispelled words.  Closing now...',
		'OK' => 'OK',
		'Original word' => 'Original word',
		'Please wait. Calling spell checker.' => 'Please wait. Calling spell checker.',
		'Please wait: changing dictionary to' => 'Please wait: changing dictionary to',
		'HTMLArea Spell Checker' => 'HTMLArea Spell Checker',
		'QUIT_CONFIRMATION' => 'This will drop changes and quit spell checker.  Please confirm.',
		'Re-check' => 'Re-check',
		'Replace all' => 'Replace all',
		'Replace with' => 'Replace with',
		'Replace' => 'Replace',
		'Learn' => 'Add to dictionary',
		'Revert' => 'Revert',
		'SC-spell-check' => 'Spell-check',
		'Suggestions' => 'Suggestions',
		'One occurrence' => 'One occurrence',
		'Two occurrences' => 'Two occurrences',
		'occurrences' => 'occurrences',
		'of the word' => 'of the word',
		'was found.' => 'was found.',
		'were found.' => 'were found.',
		'Document information' => 'Document information',
		'No information available' => 'No information available',
		'Total words' => 'Total words',
		'Misspelled words' => 'Misspelled words',
		'Total suggestions' => 'Total suggestions',
		'Total words suggested' => 'Total words suggested',
		'Spelling checked in' => 'Spelling checked in',
		'seconds' => 'seconds',
		'pliz weit ;-)' => 'Please wait...',
	),
	'dk' => Array (
		'Spell Checker' => 'Stavekontrol',
		'CONFIRM_LINK_CLICK' => 'Bekrжft venligst at du шnsker at еbne dette link',
		'Cancel' => 'Afbryd',
		'Dictionary' => 'Ordbog',
		'Finished list of mispelled words' => 'Fжrdig liste over forkert stavede ord',
		'I will open it in a new page.' => 'Jeg vil еbne i et nyt vindue',
		'Ignore all' => 'Ignorйr alle',
		'Ignore' => 'Ignorйr',
		'NO_ERRORS' => 'Ingen',
		'NO_ERRORS_CLOSING' => 'Stavekontrol gennemfшrt, der blev ikke fundet nogle forkert stavede ord. Lukker nu...',
		'OK' => 'OK',
		'Original word' => 'Oprindeligt ord',
		'Please wait. Calling spell checker.' => 'Vent venligst. Kommunikerer med stavekontrollen.',
		'Please wait: changing dictionary to' => 'Vent venligst: Skifter ordbog til',
		'HTMLArea Spell Checker' => 'HTMLArea stavekontrol',
		'QUIT_CONFIRMATION' => 'Dette vil droppe жndringer og lukke stavekontrollen. Bekrжft venligst.',
		'Re-check' => 'Check igen',
		'Replace all' => 'Erstat alle',
		'Replace with' => 'Erstat med',
		'Replace' => 'Erstat',
		'Learn' => 'Tilfшj til ordbog',
		'Revert' => 'Gе tilbage',
		'SC-spell-check' => 'Stavekontrol',
		'Suggestions' => 'Forslag',
		'One occurrence' => '1 forekomst',
		'Two occurrences' => '2 forekomster',
		'occurrences' => 'forekomster',
		'of the word' => 'af ordet',
		'was found.' => 'blev fundet.',
		'were found.' => 'blev fundet.',
		'Document information' => 'Dokumentinformation',
		'No information available' => 'Ingen information tilgжngelig',
		'Total words' => 'Antal ord',
		'Misspelled words' => 'Forkert stavede ord',
		'Total suggestions' => 'Antal foreslag',
		'Total words suggested' => 'Antal ord foreslеet',
		'Spelling checked in' => 'Stavekontrollen blev gennemfшrt pе',
		'seconds' => 'sekunder',
		'pliz weit ;-)' => 'Vent venligst ;-)',
	),
	'de' => Array (
		'Spell Checker' => 'Spell Checker',
		'CONFIRM_LINK_CLICK' => 'Bitte bestдtigen Sie, dass Sie diesem Link folgen mцchten',
		'Cancel' => 'Abbrechen',
		'Dictionary' => 'Wцrterbuch',
		'Finished list of mispelled words' => 'Fertige Liste der Fehler',
		'I will open it in a new page.' => 'Ich werde eine neue Seite цffnen.',
		'Ignore all' => 'Alle ignorieren',
		'Ignore' => 'Ignorieren',
		'NO_ERRORS' => 'Im ausgewдhlten Wцrterbuch wurden keine Fehler gefunden.',
		'NO_ERRORS_CLOSING' => 'Fehlersuche beendet, es wurden keine Fehler gefunden.  Die Suche wird nun beendet...',
		'OK' => 'OK',
		'Original word' => 'Ursprьngliches Wort',
		'Please wait. Calling spell checker.' => 'Bitte warten. Die Rechtschreibprьfung wird aufgerufen.',
		'Please wait: changing dictionary to' => 'Bitte warten: das Wцrterbuch wird geдndert nach',
		'HTMLArea Spell Checker' => 'HTMLArea Rechtschreibprьfung',
		'QUIT_CONFIRMATION' => 'Hierdurch werden die Дnderungen verworfen und die Rechtschreibprьfung beendet. Bitte bestдtigen.',
		'Re-check' => 'Nochmals prьfen',
		'Replace all' => 'Alle ersetzen',
		'Replace with' => 'Ersetzen durch',
		'Replace' => 'Ersetzen',
		'Revert' => 'Umkehren',
		'SC-spell-check' => 'Rechtschreibprьfung',
		'Suggestions' => 'Vorschlдge',
		'One occurrence' => 'Einmal',
		'Two occurrences' => 'Zweimal',
		'occurrences' => 'Anzahl Vorkommen',
		'of the word' => 'des Wortes',
		'was found.' => 'wurde gefunden.',
		'were found.' => 'wurden gefunden.',
		'Document information' => 'Dokumentinformation',
		'No information available' => 'Keine information verfьgbar',
		'Total words' => 'Totale Anzahl Wцrter',
		'Misspelled words' => 'Fehlerhafte Wцrter',
		'Total suggestions' => 'Total Anzahl Vorschlдge',
		'Total words suggested' => 'Total Anzahl vorgeschlagener Wцrter',
		'Spelling checked in' => 'Rechtschreibprьfung durchgefьhrt in',
		'seconds' => 'Sekunden',
		'pliz weit ;-)' => 'Bidde wahten ;-)',
	),
	'no' => Array (
		'Spell Checker' => 'Rettskrivning',
		'CONFIRM_LINK_CLICK' => 'Vennligst bekreft at du vil еpne denne linken',
		'Cancel' => 'Avbryt',
		'Dictionary' => 'Ordbok',
		'Finished list of mispelled words' => 'Ferdig liste over feilstavede ord',
		'I will open it in a new page.' => 'Jeg vil еpne det pе en ny side',
		'Ignore all' => 'Ignorer alle',
		'Ignore' => 'Ignorer',
		'NO_ERRORS' => 'Ingen feilstavede ord ble funnet',
		'NO_ERRORS_CLOSING' => 'Rettskrivningskontrollen er ferdig. Ingen feil ble funnet. Lukker nе...',
		'OK' => 'OK',
		'Original word' => 'Opprinnelig ord',
		'Please wait. Calling spell checker.' => 'Vennligst vent. Henter rettskrivningskontroll.',
		'Please wait: changing dictionary to' => 'Vennligst vent: Endrer ordbok til',
		'HTMLArea Spell Checker' => 'HTMLArea Rettskrivningskontroll',
		'QUIT_CONFIRMATION' => 'Dette vil fjerne alle endringer og avslutte rettskrivningskontrollen.',
		'Re-check' => 'Sjekk igjen',
		'Replace all' => 'Bytt ut alle',
		'Replace with' => 'Bytt ut med',
		'Replace' => 'Bytt ut',
		'Revert' => 'Gе tilbake',
		'SC-spell-check' => 'Rettskrivningskontroll',
		'Suggestions' => 'Forslag',
		'One occurrence' => '1 forekomst',
		'Two occurrences' => '2 forekomster',
		'occurrences' => 'forekomster',
		'of the word' => 'av order',
		'was found.' => 'ble funnet.',
		'were found.' => 'ble funnet.',
		'Document information' => 'Dokumentinformasjon.',
		'No information available' => 'Ingen informasjon tilgjengelig.',
		'Total words' => 'Totalt antall ord.',
		'Misspelled words' => 'Ord med feil',
		'Total suggestions' => 'Antall forslag',
		'Total words suggested' => 'Antall foreslеtte ord',
		'Spelling checked in' => 'Rettskrivningen ble undersшkt pе',
		'seconds' => 'sekunder',
		'pliz weit ;-)' => 'Vennligst vent',
	),
	'it' => Array (
		'Spell Checker' => 'Controllo Ortografico',
		'CONFIRM_LINK_CLICK' => 'Conferma per aprire questo link',
		'Cancel' => 'Cancella',
		'Dictionary' => 'Dizionario',
		'Finished list of mispelled words' => 'Terminata la lista di parole non corrette',
		'I will open it in a new page.' => 'Lo aprirт in una nuova pagina',
		'Ignore all' => 'Ignora tutto',
		'Ignore' => 'Ignora',
		'NO_ERRORS' => 'Non sono state trovate parole non corrette con il dizionario selezionato.',
		'NO_ERRORS_CLOSING' => 'Controllo ortografico completato, non и stata tovata alcuna parola scorretta. Sto chiudendo...',
		'OK' => 'OK',
		'Original word' => 'Parola originale',
		'Please wait. Calling spell checker.' => 'Attendere prego. Sto caricando il controllo ortografico',
		'Please wait: changing dictionary to' => 'Attendere prego: sto cambiando il dizionario in',
		'HTMLArea Spell Checker' => 'Controllo Ortografico HTMLArea',
		'QUIT_CONFIRMATION' => 'Questo annullerа le modifiche e chiuderа il controllo ortografico. Conferma.',
		'Re-check' => 'Ri-controlla',
		'Replace all' => 'Sostituisci tutto',
		'Replace with' => 'Sostituisci con',
		'Replace' => 'Sostituisci',
		'Revert' => 'Inverti',
		'SC-spell-check' => 'Controllo ortografico',
		'Suggestions' => 'Suggerimenti',
		'One occurrence' => 'Un\'occorrenza',
		'Two occurrences' => 'Due occorrenze',
		'occurrences' => 'occorrenze',
		'of the word' => 'della parola',
		'was found.' => 'и stata trovata.',
		'were found.' => 'sono state trovate.',
		'Document information' => 'Informazione documento',
		'No information available' => 'Non ci sono informazioni disponibili',
		'Total words' => 'Parole totali',
		'Misspelled words' => 'Parole non corrette',
		'Total suggestions' => 'Totale suggerimenti',
		'Total words suggested' => 'Totale parole suggerite',
		'Spelling checked in' => 'Controllo ortografico effettuato in',
		'seconds' => 'secondi',
		'pliz weit ;-)' => 'attendere prego;-)',
	),
	'fr' => Array (
		'Spell Checker' => 'Vйrificateur orthographique',
		'CONFIRM_LINK_CLICK' => 'Veuillez confirmer la demande d\'ouverture de ce lien',
		'Cancel' => 'Annuler',
		'Dictionary' => 'Dictionnaire',
		'Finished list of mispelled words' => 'La liste des mots mal orthographiйs est terminйe.',
		'I will open it in a new page.' => 'Ouverture dans une nouvelle page.',
		'Ignore all' => 'Ignorer tous',
		'Ignore' => 'Ignorer',
		'NO_ERRORS' => 'Aucune faute n\'a йtй trouvйe avec le dictionnaire choisi.',
		'NO_ERRORS_CLOSING' => 'Vйrification terminйe, aucune erreur d\'orthographe n\'a йtй trouvйe. Fermeture...',
		'OK' => 'Valider',
		'Original word' => 'Mot original',
		'Please wait. Calling spell checker.' => 'Veuillez patienter. Lancement du vйrificateur orthographique.',
		'Please wait: changing dictionary to' => 'Veuillez patienter. Chargement du dictionnaire ',
		'HTMLArea Spell Checker' => 'HTMLArea - Vйrificateur orthographique',
		'QUIT_CONFIRMATION' => 'Ceci va annuler tous les changements et quitter le vйrificateur orthographique. Veuillez confirmer.',
		'Re-check' => 'Re-vйrifier',
		'Replace all' => 'Remplacer partout',
		'Replace with' => 'Remplacer par',
		'Replace' => 'Remplacer',
		'Learn' => 'Ajouter au dictionnaire',
		'Revert' => 'Rйtablir',
		'SC-spell-check' => 'Vйrifier l\'orthographe',
		'Suggestions' => 'Suggestions',
		'One occurrence' => 'Une occurrence',
		'Two occurrences' => 'Deux occurrences',
		'occurrences' => 'occurrences',
		'of the word' => 'du mot',
		'was found.' => 'a йtй trouvйe.',
		'were found.' => 'ont йtй trouvйes.',
		'Document information' => 'Information sur le document',
		'No information available' => 'Aucune information disponible',
		'Total words' => 'Nombre de mots dans le document',
		'Misspelled words' => 'Nombre de mots en erreur',
		'Total suggestions' => 'Nombre de suggestions',
		'Total words suggested' => 'Nombre total de mots suggйrйs',
		'Spelling checked in' => 'Vйrification effectuйe en',
		'seconds' => 'secondes',
		'pliz weit ;-)' => 'Veuillez patienter svp...',
	),
	'es' => Array (
		'Spell Checker' => 'Revisor ortogrбfico',
		'CONFIRM_LINK_CLICK' => 'Confirme que desea abrir este enlace',
		'Cancel' => 'Cancelar',
		'Dictionary' => 'Diccionario',
		'Finished list of mispelled words' => 'Se ha terminado la lista de palabras mal escritas',
		'I will open it in a new page.' => 'Lo abrirй en una nueva pбgina.',
		'Ignore all' => 'Ignorar todas',
		'Ignore' => 'Ignorar',
		'NO_ERRORS' => 'No se han encontrado palabras mal escritas segъn el diccionario seleccionado.',
		'NO_ERRORS_CLOSING' => 'Revisiуn ortogrбfica completada, no se encontraron palabras mal escritas. Cerrando...',
		'OK' => 'Aceptar',
		'Original word' => 'Palabra original',
		'Please wait. Calling spell checker.' => 'Espere. Llamando al revisor ortogrбfico.',
		'Please wait: changing dictionary to' => 'Espere: cambiando al diccionario',
		'HTMLArea Spell Checker' => 'HTMLArea - Revisor ortogrбfico',
		'QUIT_CONFIRMATION' => 'Esto anularб los cambios y se abandonarб la revisiуn ortogrбfica. їQuiere continuar?',
		'Re-check' => 'Volver a revisar',
		'Replace all' => 'Sustituir todas',
		'Replace with' => 'Sustituir con',
		'Replace' => 'Sustituir',
		'Learn' => 'Aсadir al diccionario',
		'Revert' => 'Restablecer',
		'SC-spell-check' => 'Revisar ortografнa',
		'Suggestions' => 'Sugerencias',
		'One occurrence' => 'Una ocurrencia',
		'Two occurrences' => 'Dos ocurrencias',
		'occurrences' => 'ocurrencias',
		'of the word' => 'de la palabra',
		'was found.' => 'se ha encontrado.',
		'were found.' => 'se han encontrado.',
		'Document information' => 'Informaciуn sobre el documento',
		'No information available' => 'Ninguna informaciуn disponible',
		'Total words' => 'Nъmero de palabras en el documento',
		'Misspelled words' => 'Nъmero de palabras mal escritas',
		'Total suggestions' => 'Nъmero de sugerencias',
		'Total words suggested' => 'Nъmero total de palabras sugeridas',
		'Spelling checked in' => 'Revisiуn realizada en',
		'seconds' => 'segundos',
		'pliz weit ;-)' => 'Espere par favor...',
	),
	'nl' => Array (
		'Spell Checker' => 'Spellingscontrole',
		'CONFIRM_LINK_CLICK' => 'Bevestig AUB dat u deze link wilt openen',
		'Cancel' => 'Annuleren',
		'Dictionary' => 'Woordenboek',
		'Finished list of mispelled words' => 'Volledige lijst met verkeerd gespelde woorden',
		'I will open it in a new page.' => 'Ik zal het openen in een nieuwe pagina',
		'Ignore all' => 'Negeer alles',
		'Ignore' => 'Negeer',
		'NO_ERRORS' => 'Geen verkeerd gespelde woorden gevonden met het geselecteerde woordenboek',
		'NO_ERRORS_CLOSING' => 'Spellingscontrole compleet, geen verkeerd gespelde woorden gevonden. Bezig met afsluiten...',
		'OK' => 'OK',
		'Original word' => 'Origineel woord',
		'Please wait. Calling spell checker.' => 'Wachten AUB. Spellings controle wordt aangeroepen.',
		'Please wait: changing dictionary to' => 'Wachten AUB: woordenboek aan het veranderen naar',
		'HTMLArea Spell Checker' => 'HTMLArea Spellingscontrole',
		'QUIT_CONFIRMATION' => 'Dit zal de aanpassingen annuleren en de spellingscontrole afsluiten. Bevestig AUB.',
		'Re-check' => 'Opnieuw controleren',
		'Replace all' => 'Alles vervangen',
		'Replace with' => 'Vervangen met',
		'Replace' => 'Vervangen',
		'Revert' => 'Keer terug',
		'SC-spell-check' => 'Spellings-controle',
		'Suggestions' => 'Voorstellen',
		'One occurrence' => 'Een keer dat',
		'Two occurrences' => 'Twee keer dat',
		'occurrences' => 'keren dat',
		'of the word' => 'het woord',
		'was found.' => 'is gevonden',
		'were found.' => 'zijn gevonden.',
		'Document information' => 'Document informatie',
		'No information available' => 'Geen informatie beschikbaar',
		'Total words' => 'Totaal aantal woorden',
		'Misspelled words' => 'Fout gespelde woorden',
		'Total suggestions' => 'Totaal aantal voorstellen',
		'Total words suggested' => 'Totaal aantal voorgestelde woorden',
		'Spelling checked in' => 'Spelling gecontroleerd in',
		'seconds' => 'seconden',
		'pliz weit ;-)' => 'ff wachten ;-)',
	),
	'cz' => Array (
	),
	'pl' => Array (
	),
	'si' => Array (
	),
	'fi' => Array (
		'Spell Checker' => 'Oikeinkirjotuksen tarkistus',
		'CONFIRM_LINK_CLICK' => 'Vahvista ettд haluat avata tдmдn linkin',
		'Cancel' => 'Peruuta',
		'Dictionary' => 'Sanakirja',
		'Finished list of mispelled words' => 'Vддrinkirjoitettujen sanojen lista valmis',
		'I will open it in a new page.' => 'Avaan sen uudella sivulla',
		'Ignore all' => 'Ohita kaikki',
		'Ignore' => 'Ohita',
		'NO_ERRORS' => 'Valitulla sanakirjalla ei lцytynyt vддrinkirjoitettuja sanoja',
		'NO_ERRORS_CLOSING' => 'Oikoluku valmis',
		'OK' => 'OK',
		'Original word' => 'Alkuperдinen sana',
		'Please wait. Calling spell checker.' => 'Ole hyvд ja odota. Kutsumme oikolukua.',
		'Please wait: changing dictionary to' => 'Ole hyvд ja odota. vaihdamme sanakirjan',
		'HTMLArea Spell Checker' => 'HTMLArea oikoluku',
		'QUIT_CONFIRMATION' => 'Tдmд unohtaa muutokset ja lopettaa oikoluvun. Ole hyvд ja vahvista.',
		'Re-check' => 'Tarkista uudelleen',
		'Replace all' => 'Korvaa kaikki',
		'Replace with' => 'Korvaa',
		'Replace' => 'Korvaa',
		'Learn' => 'Lisдд sanakirjaan',
		'Revert' => 'Palauta',
		'SC-spell-check' => 'Oikolue',
		'Suggestions' => 'Ehdotukset',
		'One occurrence' => 'Yksi esiintymд',
		'Two occurrences' => 'Kaiksi esiintymдд',
		'occurrences' => 'esiintymдt',
		'of the word' => 'sanan',
		'was found.' => 'lцytyi.',
		'were found.' => 'lцytyi.',
		'Document information' => 'Asiakirjan tiedot',
		'No information available' => 'Ei tietoja saatavilla',
		'Total words' => 'Sanoja yhteensд',
		'Misspelled words' => 'Vддrinkirjoitettuja sanoja',
		'Total suggestions' => 'Ehdotuksia yhteensд',
		'Total words suggested' => 'Ehdotettuja sanoja yhteensд',
		'Spelling checked in' => 'Oikoluvussa tarkistettiin',
		'seconds' => 'sekuntia',
		'pliz weit ;-)' => 'Ole hyvд ja odota.',
	),
	'tr' => Array (
	),
	'se' => Array (
	),
	'pt' => Array (
	),
	'ru' => Array (
		'Spell Checker' => 'Проверка правописания',
		'CONFIRM_LINK_CLICK' => 'Пожалуйста, подтвердите, что Вы хотите открыть эту ссылку',
		'Cancel' => 'Отмена',
		'Dictionary' => 'Словарь',
		'Finished list of mispelled words' => 'Законченый список слов с ошибками',
		'I will open it in a new page.' => 'Я открою его в новой странице.',
		'Ignore all' => 'Игнорировать все',
		'Ignore' => 'Игнорировать',
		'NO_ERRORS' => 'Слова с ошибками не найдены при использовании выбраного словаря',
		'NO_ERRORS_CLOSING' => 'Проверка правописания окончена, ошибок не найдено. Закрываемся...',
		'OK' => 'ОК',
		'Original word' => 'Оригинальное слово',
		'Please wait. Calling spell checker.' => 'Пожалуйста, подождите. Вызываю проверку правописания.',
		'Please wait: changing dictionary to' => 'Пожалуйста, подождите. Изменяю словарь на',
		'HTMLArea Spell Checker' => 'Проверка правописания',
		'QUIT_CONFIRMATION' => 'Это отменит все изменения и закроет проверку правописания. Продолжать?',
		'Re-check' => 'Проверить ещё раз',
		'Replace all' => 'Заменить все',
		'Replace with' => 'Заменить на',
		'Replace' => 'Заменить',
		'Revert' => 'Восстановить',
		'SC-spell-check' => 'Правописание',
		'Suggestions' => 'Предположения',
		'One occurrence' => 'Одно вхождение',
		'Two occurrences' => 'Два вхождения',
		'occurrences' => 'вхождени[й/е]',
		'of the word' => 'слова',
		'was found.' => 'было найдено',
		'were found.' => 'было найдено',
		'Document information' => 'Информация о документе',
		'No information available' => 'Информации нет',
		'Total words' => 'Всего слов',
		'Misspelled words' => 'Слов с ошибками',
		'Total suggestions' => 'Всего предположений',
		'Total words suggested' => 'Всего предложено слов',
		'Spelling checked in' => 'Проверено в',
		'seconds' => 'секунд',
		'pliz weit ;-)' => 'пажалуста падаждити ;-)',
	),
	'ro' => Array (
	),
	'ch' => Array (
	),
	'sk' => Array (
		'Spell Checker' => 'Kontrola pravopisu',
		'CONFIRM_LINK_CLICK' => 'Prosнm potvrпte, ћe chcete otvoriќ tento odkaz',
		'Cancel' => 'Zruљiќ',
		'Dictionary' => 'Slovnнk',
		'Finished list of mispelled words' => 'Skonиenй listovanie chybnэch slov',
		'I will open it in a new page.' => 'Chcem otvoriќ v novom okne.',
		'Ignore all' => 'Ignorovaќ vљetko',
		'Ignore' => 'Ignorovaќ',
		'NO_ERRORS' => 'Ћiadne chbnй slovб nбjdenй so zvolenэm slovnнkom',
		'NO_ERRORS_CLOSING' => 'Kontrola pravopisu skonиenб, neboli nбjdenй chybnй slovб. Zatvбram ...',
		'OK' => 'OK',
		'Original word' => 'Pфvodnй slovo',
		'Please wait. Calling spell checker.' => 'Иakajte prosнm. Otvбram kontrolu pravopisu.',
		'Please wait: changing dictionary to' => 'Иakajte prosнm. Menнm slovnнk na',
		'HTMLArea Spell Checker' => 'HTMLArea kontrola pravopisu',
		'QUIT_CONFIRMATION' => 'Toto zruљн zmeny a zatvorн kontrolu pravopisu. Prosнm potvrпte.',
		'Re-check' => 'Znova skontrolovaќ',
		'Replace all' => 'Nahradiќ vљetko',
		'Replace with' => 'Nahradiќ s',
		'Replace' => 'Nahradiќ',
		'Learn' => 'Pridaќ do slovnнka',
		'Revert' => 'Vrбtiќ',
		'SC-spell-check' => 'Kontrola pravopisu',
		'Suggestions' => 'Nбvrhy',
		'One occurrence' => 'Jeden vэskyt',
		'Two occurrences' => 'Dva vэskyty',
		'occurrences' => 'vэskyty',
		'of the word' => 'slova',
		'was found.' => 'bol nбjdenэ.',
		'were found.' => 'boli nбjdenй.',
		'Document information' => 'Informбcie o dokumente',
		'No information available' => 'Nie sъ dostupnй ћiadne informбcie',
		'Total words' => 'Poиet slov:',
		'Misspelled words' => 'Chybnй slovб:',
		'Total suggestions' => 'Poиet nбvrhov:',
		'Total words suggested' => 'Poиet slovnэch nбvrhov:',
		'Spelling checked in' => 'Pravopis kontrolovanэ v',
		'seconds' => 'sekъnd',
		'pliz weit ;-)' => 'Иakajte prosнm ...',
	),
	'lt' => Array (
	),
	'is' => Array (
	),
	'hr' => Array (
	),
	'hu' => Array (
	),
	'gl' => Array (
	),
	'th' => Array (
	),
	'gr' => Array (
	),
	'hk' => Array (
	),
	'eu' => Array (
	),
	'bg' => Array (
	),
	'br' => Array (
		'Spell Checker' => 'Corretor Ortogrбfico',
		'CONFIRM_LINK_CLICK' => 'Por favor confirme que vocк quer abrir este link',
		'Cancel' => 'Cancelar',
		'Dictionary' => 'Dicionбrio',
		'Finished list of mispelled words' => 'Finalizada a lista de palavras erradas',
		'pliz weit ;-)' => 'calminha aн! ;-)',
	),
	'et' => Array (
	),
	'ar' => Array (
	),
	'he' => Array (
	),
	'ua' => Array (
	),
	'lv' => Array (
	),
	'jp' => Array (
	),
	'vn' => Array (
	),
	'ca' => Array (
	),
	'ba' => Array (
	),
	'kr' => Array (
	),
	'eo' => Array (
	),
	'my' => Array (
	),
	'hi' => Array (
	),
);
?>