<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2009-10-26 22:04
$extensionPath = \TYPO3\CMS\Core\Utility\ExtensionManagementUtility::extPath('recordlist');
return array(
	'sc_db_list' => $extensionPath . 'mod1/index.php'
);
?>