<?php
return array(
	'TYPO3\\CMS\\Form\\Domain\\Model\\Attribute\\AcceptcharsetAttribute' => \TYPO3\CMS\Form\Domain\Model\Attribute\AcceptCharsetAttribute::class,
	'TYPO3\\CMS\\Form\\Domain\\Model\\Element\\CheckboxgroupElement' => \TYPO3\CMS\Form\Domain\Model\Element\CheckboxGroupElement::class,
	'TYPO3\\CMS\\Form\\Domain\\Model\\Element\\RadiogroupElement' => \TYPO3\CMS\Form\Domain\Model\Element\RadioGroupElement::class,
	'TYPO3\\CMS\\Form\\Domain\\Model\\Json\\CheckboxgroupJsonElement' => \TYPO3\CMS\Form\Domain\Model\Json\CheckboxGroupJsonElement::class,
	'TYPO3\\CMS\\Form\\Domain\\Model\\Json\\RadiogroupJsonElement' => \TYPO3\CMS\Form\Domain\Model\Json\RadioGroupJsonElement::class,
	'TYPO3\\CMS\\Form\\Filter\\RegexpFilter' => \TYPO3\CMS\Form\Filter\RegExpFilter::class,
	'TYPO3\\CMS\\Form\\Filter\\StripnewlinesFilter' => \TYPO3\CMS\Form\Filter\StripNewLinesFilter::class,
	'TYPO3\\CMS\\Form\\Filter\\TitlecaseFilter' => \TYPO3\CMS\Form\Filter\TitleCaseFilter::class,
	'TYPO3\\CMS\\Form\\Filter\\UppercaseFilter' => \TYPO3\CMS\Form\Filter\UpperCaseFilter::class,
	'TYPO3\\CMS\\Form\\Validation\\FileallowedtypesValidator' => \TYPO3\CMS\Form\Validation\FileAllowedTypesValidator::class,
	'TYPO3\\CMS\\Form\\Validation\\FilemaximumsizeValidator' => \TYPO3\CMS\Form\Validation\FileMaximumSizeValidator::class,
	'TYPO3\\CMS\\Form\\Validation\\FileminimumsizeValidator' => \TYPO3\CMS\Form\Validation\FileMinimumSizeValidator::class,
	'TYPO3\\CMS\\Form\\Validation\\GreaterthanValidator' => \TYPO3\CMS\Form\Validation\GreaterThanValidator::class,
	'TYPO3\\CMS\\Form\\Validation\\InarrayValidator' => \TYPO3\CMS\Form\Validation\InArrayValidator::class,
	'TYPO3\\CMS\\Form\\Validation\\RegexpValidator' => \TYPO3\CMS\Form\Validation\RegExpValidator::class,
	'TYPO3\\CMS\\Form\\View\\Confirmation\\Element\\CheckboxgroupElementView' => \TYPO3\CMS\Form\View\Confirmation\Element\CheckboxGroupElementView::class,
	'TYPO3\\CMS\\Form\\View\\Confirmation\\Element\\RadiogroupElementView' => \TYPO3\CMS\Form\View\Confirmation\Element\RadioGroupElementView::class,
	'TYPO3\\CMS\\Form\\View\\Form\\Element\\CheckboxgroupElementView' => \TYPO3\CMS\Form\View\Form\Element\CheckboxGroupElementView::class,
	'TYPO3\\CMS\\Form\\View\\Form\\Element\\RadiogroupElementView' => \TYPO3\CMS\Form\View\Form\Element\RadioGroupElementView::class,
	'TYPO3\\CMS\\Form\\View\\Mail\\Html\\Element\\CheckboxgroupElementView' => \TYPO3\CMS\Form\View\Mail\Html\Element\CheckboxGroupElementView::class,
	'TYPO3\\CMS\\Form\\View\\Mail\\Html\\Element\\RadiogroupElementView' => \TYPO3\CMS\Form\View\Mail\Html\Element\RadioGroupElementView::class,
	'TYPO3\\CMS\\Form\\View\\Mail\\Plain\\Element\\CheckboxgroupElementView' => \TYPO3\CMS\Form\View\Mail\Plain\Element\CheckboxGroupElementView::class,
	'TYPO3\\CMS\\Form\\View\\Mail\\Plain\\Element\\RadiogroupElementView' => \TYPO3\CMS\Form\View\Mail\Plain\Element\RadioGroupElementView::class,
	'TYPO3\\CMS\\Form\\Filter\\RemovexssFilter' => \TYPO3\CMS\Form\Filter\RemoveXssFilter::class,
);