<?php

declare(strict_types=1);

/*
 * This file is part of the TYPO3 CMS project.
 *
 * It is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License, either version 2
 * of the License, or any later version.
 *
 * For the full copyright and license information, please read the
 * LICENSE.txt file that was distributed with this source code.
 *
 * The TYPO3 project - inspiring people to share!
 */

namespace TYPO3\CMS\Seo\XmlSitemap;

use Psr\Http\Message\ServerRequestInterface;
use TYPO3\CMS\Core\Utility\GeneralUtility;
use TYPO3\CMS\Frontend\ContentObject\ContentObjectRenderer;

/**
 * Base class for XmlSitemapProviders to extend
 *
 * @deprecated since TYPO3 v15.0, will be removed in TYPO3 v16.0. Implement
 *             XmlSitemapDataProviderInterface directly instead: Runtime information is handed over
 *             as XmlSitemapRequest to getSitemap(), the constructor is free for dependency
 *             injection. This class is kept in v15 to ease compatibility with TYPO3 v14.
 */
abstract class AbstractXmlSitemapDataProvider
{
    protected string $key;
    protected array $items = [];
    protected array $config = [];
    protected ContentObjectRenderer $cObj;
    protected int $numberOfItemsPerPage = 1000;
    protected ServerRequestInterface $request;

    public function __construct(ServerRequestInterface $request, string $key, array $config = [], ?ContentObjectRenderer $cObj = null)
    {
        trigger_error(
            'Extending AbstractXmlSitemapDataProvider (' . static::class . ') is deprecated since'
            . ' TYPO3 v15.0 and will stop working in TYPO3 v16.0. Implement'
            . ' XmlSitemapDataProviderInterface->getSitemap() instead.',
            E_USER_DEPRECATED
        );
        $this->key = $key;
        $this->config = $config;
        $this->request = $request;
        $this->cObj = $cObj ?? GeneralUtility::makeInstance(ContentObjectRenderer::class);
        $this->cObj->setRequest($request);
    }

    /**
     * Bridges legacy providers to XmlSitemapDataProviderInterface. The items have already been
     * generated by the constructor of the concrete provider, so the XmlSitemapRequest is not
     * evaluated here.
     *
     * This method is intentionally implemented although this class does not declare
     * XmlSitemapDataProviderInterface: Extensions declaring the interface on their own provider
     * class stay functional this way.
     */
    public function getSitemap(XmlSitemapRequest $sitemapRequest): XmlSitemap
    {
        return XmlSitemap::create(
            fn(): array => $this->getItems(),
            $this->getLastModified(),
            $this->getNumberOfPages(),
        );
    }

    public function getKey(): string
    {
        return $this->key;
    }

    public function getNumberOfPages(): int
    {
        return (int)ceil(count($this->items) / $this->numberOfItemsPerPage);
    }

    public function getLastModified(): int
    {
        $lastMod = 0;
        foreach ($this->items as $item) {
            if ((int)($item['lastMod'] ?? 0) > $lastMod) {
                $lastMod = (int)$item['lastMod'];
            }
        }

        return $lastMod;
    }

    protected function defineUrl(array $data): array
    {
        return $data;
    }

    public function getItems(): array
    {
        $pageNumber = (int)($this->request->getQueryParams()['tx_seo']['page'] ?? 0);
        $page = $pageNumber > 0 ? $pageNumber : 0;
        $items = array_slice(
            $this->items,
            $page * $this->numberOfItemsPerPage,
            $this->numberOfItemsPerPage
        );

        return array_map([$this, 'defineUrl'], $items);
    }
}
