<!DOCTYPE html>
<html>
<head>
	<title>The Install Tool is locked</title>
	<link rel="stylesheet" type="text/css" href="../Resources/Public/Stylesheets/Action/Common/EarlyExit.css?<?= $this->variables['time'] ?>" />
</head>
<body>
<div id="container">
	<h1>TYPO3</h1>
	<div class="typo3-message message-warning">
		<h2>The Install Tool is locked</h2>
		<p>
			To enable the Install Tool, the file ENABLE_INSTALL_TOOL must be created.
		</p>
		<ul>
			<li>
				In the typo3conf/ folder, create a file named ENABLE_INSTALL_TOOL. The file name is
				case sensitive, but the file itself can simply be an empty file.
			</li>
			<li>
				You are recommended to log out from the Install Tool after finishing your work.
				The file will then automatically be deleted.
			</li>
		</ul>
		<p>
			For security reasons, it is highly recommended that you either rename or delete the file after the operation is finished.
		</p>
		<p>
			As an additional security measure, if the file is older than one hour, TYPO3 will automatically delete it. The file must be writable by the web server user.
		</p>
	</div>
</div>
</body>
</html>
