<!DOCTYPE html>
<html>
<head>
	<title>The Install Tool is locked</title>
	<link rel="stylesheet" type="text/css" href="../Resources/Public/Css/Action/Common/EarlyExit.css?<?= $this->variables['time'] ?>" />
</head>
<body>
<div id="container">
	<h1>TYPO3</h1>

	<div class="typo3-message message-warning">
		<h2>The Install Tool is locked</h2>

		<p>
			To enable the Install Tool, the file <strong>ENABLE_INSTALL_TOOL</strong>
			must be created in the directory <strong>typo3conf/</strong>.
			The file must be writable by the web server user.
			The filename is case-sensitive but the file itself can be empty.
		</p>

		<p>
			<strong>Security note:</strong>
			When you are finished with the Install Tool, you should rename or delete this file.
			It will automatically be deleted if you log out of the Install Tool or if the file is older than one hour.
		</p>
	</div>
</div>
</body>
</html>