<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2011-12-20 09:30

$extensionPath = t3lib_extMgm::extPath('extjs3_compat');
return array(
	'tx_extjs3compat_loader' => $extensionPath . 'Tx_extjs3compat_Loader.php',
);
?>