<?php

	// $id$

define('TYPO3_REQUIREMENTS_MINIMUM_PHP', '5.2.0');

define('TYPO3_REQUIREMENTS_MINIMUM_PHP_MEMORY_LIMIT', '32M');
define('TYPO3_REQUIREMENTS_RECOMMENDED_PHP_MEMORY_LIMIT', '64M');

?>