<?php
return array(
	'Tx_Workspaces_Controller_AbstractController' => 'TYPO3\\CMS\\Workspaces\\Controller\\AbstractController',
	'Tx_Workspaces_Controller_PreviewController' => 'TYPO3\\CMS\\Workspaces\\Controller\\PreviewController',
	'Tx_Workspaces_Controller_ReviewController' => 'TYPO3\\CMS\\Workspaces\\Controller\\ReviewController',
	'Tx_Workspaces_Domain_Model_CombinedRecord' => 'TYPO3\\CMS\\Workspaces\\Domain\\Model\\CombinedRecord',
	'Tx_Workspaces_Domain_Model_DatabaseRecord' => 'TYPO3\\CMS\\Workspaces\\Domain\\Model\\DatabaseRecord',
	'Tx_Workspaces_ExtDirect_AbstractHandler' => 'TYPO3\\CMS\\Workspaces\\ExtDirect\\AbstractHandler',
	'Tx_Workspaces_ExtDirect_ActionHandler' => 'TYPO3\\CMS\\Workspaces\\ExtDirect\\ActionHandler',
	'Tx_Workspaces_ExtDirect_Server' => 'TYPO3\\CMS\\Workspaces\\ExtDirect\\ExtDirectServer',
	'Tx_Workspaces_ExtDirect_MassActionHandler' => 'TYPO3\\CMS\\Workspaces\\ExtDirect\\MassActionHandler',
	'Tx_Workspaces_ExtDirect_PagetreeCollectionsProcessor' => 'TYPO3\\CMS\\Workspaces\\ExtDirect\\PagetreeCollectionsProcessor',
	'Tx_Workspaces_ExtDirect_ToolbarMenu' => 'TYPO3\\CMS\\Workspaces\\ExtDirect\\ToolbarMenu',
	'Tx_Workspaces_ExtDirect_WorkspaceSelectorToolbarItem' => 'TYPO3\\CMS\\Workspaces\\ExtDirect\\WorkspaceSelectorToolbarItem',
	'Tx_Workspaces_Service_Befunc' => 'TYPO3\\CMS\\Workspaces\\Hook\\BackendUtilityHook',
	'Tx_Workspaces_Service_Tcemain' => 'TYPO3\\CMS\\Workspaces\\Hook\\DataHandlerHook',
	'Tx_Workspaces_Service_Fehooks' => 'TYPO3\\CMS\\Workspaces\\Hook\\TypoScriptFrontendControllerHook',
	'Tx_Workspaces_Service_AutoPublish' => 'TYPO3\\CMS\\Workspaces\\Service\\AutoPublishService',
	'Tx_Workspaces_Service_GridData' => 'TYPO3\\CMS\\Workspaces\\Service\\GridDataService',
	'Tx_Workspaces_Service_History' => 'TYPO3\\CMS\\Workspaces\\Service\\HistoryService',
	'Tx_Workspaces_Service_Integrity' => 'TYPO3\\CMS\\Workspaces\\Service\\IntegrityService',
	'Tx_Workspaces_Service_Stages' => 'TYPO3\\CMS\\Workspaces\\Service\\StagesService',
	'Tx_Workspaces_Service_Workspaces' => 'TYPO3\\CMS\\Workspaces\\Service\\WorkspaceService',
	'Tx_Workspaces_Service_AutoPublishTask' => 'TYPO3\\CMS\\Workspaces\\Task\\AutoPublishTask',
	'Tx_Workspaces_Service_CleanupPreviewLinkTask' => 'TYPO3\\CMS\\Workspaces\\Task\\CleanupPreviewLinkTask',
);
?>