<?php
/*
 * Register necessary class names with autoloader
 *
 */
$extensionPath = t3lib_extMgm::extPath('form');
$classesPath = $extensionPath . '/Classes/';
$controllerPath = $classesPath . 'Controller/';
$domainPath = $classesPath . 'Domain/';
$systemPath = $classesPath . 'System/';
$viewPath = $classesPath . 'View/';

return array(
	'tx_form_domain_factory_typoscript' => $domainPath . 'Factory/Typoscript.php',
	'tx_form_domain_factory_jsontotyposcript' => $domainPath . 'Factory/JsonToTyposcript.php',
	'tx_form_domain_factory_typoscripttojson' => $domainPath . 'Factory/TyposcriptToJson.php',

	'tx_form_domain_model_additional_abstract' => $domainPath . 'Model/Additional/Abstract.php',
	'tx_form_domain_model_additional_additional' => $domainPath . 'Model/Additional/Additional.php',
	'tx_form_domain_model_additional_error' => $domainPath . 'Model/Additional/Error.php',
	'tx_form_domain_model_additional_label' => $domainPath . 'Model/Additional/Label.php',
	'tx_form_domain_model_additional_legend' => $domainPath . 'Model/Additional/Legend.php',
	'tx_form_domain_model_additional_interface' => $domainPath . 'Model/Additional/Interface.php',
	'tx_form_domain_model_additional_mandatory' => $domainPath . 'Model/Additional/Mandatory.php',

	'tx_form_domain_model_attributes_abstract' => $domainPath . 'Model/Attributes/Abstract.php',
	'tx_form_domain_model_attributes_accept' => $domainPath . 'Model/Attributes/Accept.php',
	'tx_form_domain_model_attributes_acceptcharset' => $domainPath . 'Model/Attributes/Acceptcharset.php',
	'tx_form_domain_model_attributes_accesskey' => $domainPath . 'Model/Attributes/Accesskey.php',
	'tx_form_domain_model_attributes_action' => $domainPath . 'Model/Attributes/Action.php',
	'tx_form_domain_model_attributes_alt' => $domainPath . 'Model/Attributes/Alt.php',
	'tx_form_domain_model_attributes_attributes' => $domainPath . 'Model/Attributes/Attributes.php',
	'tx_form_domain_model_attributes_checked' => $domainPath . 'Model/Attributes/Checked.php',
	'tx_form_domain_model_attributes_class' => $domainPath . 'Model/Attributes/Class.php',
	'tx_form_domain_model_attributes_cols' => $domainPath . 'Model/Attributes/Cols.php',
	'tx_form_domain_model_attributes_dir' => $domainPath . 'Model/Attributes/Dir.php',
	'tx_form_domain_model_attributes_disabled' => $domainPath . 'Model/Attributes/Disabled.php',
	'tx_form_domain_model_attributes_enctype' => $domainPath . 'Model/Attributes/Enctype.php',
	'tx_form_domain_model_attributes_id' => $domainPath . 'Model/Attributes/Id.php',
	'tx_form_domain_model_attributes_interface' => $domainPath . 'Model/Attributes/Interface.php',
	'tx_form_domain_model_attributes_label' => $domainPath . 'Model/Attributes/Label.php',
	'tx_form_domain_model_attributes_lang' => $domainPath . 'Model/Attributes/Lang.php',
	'tx_form_domain_model_attributes_maxlength' => $domainPath . 'Model/Attributes/Maxlength.php',
	'tx_form_domain_model_attributes_method' => $domainPath . 'Model/Attributes/Method.php',
	'tx_form_domain_model_attributes_multiple' => $domainPath . 'Model/Attributes/Multiple.php',
	'tx_form_domain_model_attributes_name' => $domainPath . 'Model/Attributes/Name.php',
	'tx_form_domain_model_attributes_readonly' => $domainPath . 'Model/Attributes/Readonly.php',
	'tx_form_domain_model_attributes_rows' => $domainPath . 'Model/Attributes/Rows.php',
	'tx_form_domain_model_attributes_selected' => $domainPath . 'Model/Attributes/Selected.php',
	'tx_form_domain_model_attributes_size' => $domainPath . 'Model/Attributes/Size.php',
	'tx_form_domain_model_attributes_src' => $domainPath . 'Model/Attributes/Src.php',
	'tx_form_domain_model_attributes_style' => $domainPath . 'Model/Attributes/Style.php',
	'tx_form_domain_model_attributes_tabindex' => $domainPath . 'Model/Attributes/Tabindex.php',
	'tx_form_domain_model_attributes_title' => $domainPath . 'Model/Attributes/Title.php',
	'tx_form_domain_model_attributes_type' => $domainPath . 'Model/Attributes/Type.php',
	'tx_form_domain_model_attributes_value' => $domainPath . 'Model/Attributes/Value.php',

	'tx_form_domain_model_form' => $domainPath . 'Model/Form.php',
	'tx_form_domain_model_element_abstract' => $domainPath . 'Model/Element/Abstract.php',
	'tx_form_domain_model_element_button' => $domainPath . 'Model/Element/Button.php',
	'tx_form_domain_model_element_captcha' => $domainPath . 'Model/Element/Captcha.php',
	'tx_form_domain_model_element_checkbox' => $domainPath . 'Model/Element/Checkbox.php',
	'tx_form_domain_model_element_checkboxgroup' => $domainPath . 'Model/Element/Checkboxgroup.php',
	'tx_form_domain_model_element_container' => $domainPath . 'Model/Element/Container.php',
	'tx_form_domain_model_element_content' => $domainPath . 'Model/Element/Content.php',
	'tx_form_domain_model_element_fieldset' => $domainPath . 'Model/Element/Fieldset.php',
	'tx_form_domain_model_element_fileupload' => $domainPath . 'Model/Element/Fileupload.php',
	'tx_form_domain_model_element_hidden' => $domainPath . 'Model/Element/Hidden.php',
	'tx_form_domain_model_element_imagebutton' => $domainPath . 'Model/Element/Imagebutton.php',
	'tx_form_domain_model_element_optgroup' => $domainPath . 'Model/Element/Optgroup.php',
	'tx_form_domain_model_element_option' => $domainPath . 'Model/Element/Option.php',
	'tx_form_domain_model_element_password' => $domainPath . 'Model/Element/Password.php',
	'tx_form_domain_model_element_radio' => $domainPath . 'Model/Element/Radio.php',
	'tx_form_domain_model_element_radiogroup' => $domainPath . 'Model/Element/Radiogroup.php',
	'tx_form_domain_model_element_reset' => $domainPath . 'Model/Element/Reset.php',
	'tx_form_domain_model_element_select' => $domainPath . 'Model/Element/Select.php',
	'tx_form_domain_model_element_submit' => $domainPath . 'Model/Element/Submit.php',
	'tx_form_domain_model_element_textarea' => $domainPath . 'Model/Element/Textarea.php',
	'tx_form_domain_model_element_textline' => $domainPath . 'Model/Element/Textline.php',

	'tx_form_domain_model_json_button' => $domainPath . 'Model/JSON/Button.php',
	'tx_form_domain_model_json_captcha' => $domainPath . 'Model/JSON/Captcha.php',
	'tx_form_domain_model_json_checkbox' => $domainPath . 'Model/JSON/Checkbox.php',
	'tx_form_domain_model_json_checkboxgroup' => $domainPath . 'Model/JSON/Checkboxgroup.php',
	'tx_form_domain_model_json_container' => $domainPath . 'Model/JSON/Container.php',
	'tx_form_domain_model_json_element' => $domainPath . 'Model/JSON/Element.php',
	'tx_form_domain_model_json_fieldset' => $domainPath . 'Model/JSON/Fieldset.php',
	'tx_form_domain_model_json_fileupload' => $domainPath . 'Model/JSON/Fileupload.php',
	'tx_form_domain_model_json_form' => $domainPath . 'Model/JSON/Form.php',
	'tx_form_domain_model_json_header' => $domainPath . 'Model/JSON/Header.php',
	'tx_form_domain_model_json_hidden' => $domainPath . 'Model/JSON/Hidden.php',
	'tx_form_domain_model_json_name' => $domainPath . 'Model/JSON/Name.php',
	'tx_form_domain_model_json_password' => $domainPath . 'Model/JSON/Password.php',
	'tx_form_domain_model_json_radio' => $domainPath . 'Model/JSON/Radio.php',
	'tx_form_domain_model_json_radiogroup' => $domainPath . 'Model/JSON/Radiogroup.php',
	'tx_form_domain_model_json_reset' => $domainPath . 'Model/JSON/Reset.php',
	'tx_form_domain_model_json_select' => $domainPath . 'Model/JSON/Select.php',
	'tx_form_domain_model_json_submit' => $domainPath . 'Model/JSON/Submit.php',
	'tx_form_domain_model_json_textarea' => $domainPath . 'Model/JSON/Textarea.php',
	'tx_form_domain_model_json_textline' => $domainPath . 'Model/JSON/Textline.php',

	'tx_form_domain_model_content' => $domainPath . 'Model/Content.php',
	'tx_form_domain_repository_content' => $domainPath . 'Repository/Content.php',

	'tx_form_system_elementcounter' => $systemPath . 'Elementcounter/Elementcounter.php',

	'tx_form_system_filter_alhabetic' => $systemPath . 'Filter/Alphabetic.php',
	'tx_form_system_filter_alphanumeric' => $systemPath . 'Filter/Alphanumeric.php',
	'tx_form_system_filter_currency' => $systemPath . 'Filter/Currency.php',
	'tx_form_system_filter_digit' => $systemPath . 'Filter/Digit.php',
	'tx_form_system_filter' => $systemPath . 'Filter/Filter.php',
	'tx_form_system_filter_integer' => $systemPath . 'Filter/Integer.php',
	'tx_form_system_filter_interface' => $systemPath . 'Filter/Interface.php',
	'tx_form_system_filter_lowercase' => $systemPath . 'Filter/Lowercase.php',
	'tx_form_system_filter_regexp' => $systemPath . 'Filter/Regexp.php',
	'tx_form_system_filter_removexss' => $systemPath . 'Filter/Removexss.php',
	'tx_form_system_filter_stripnewlines' => $systemPath . 'Filter/Stripnewlines.php',
	'tx_form_system_filter_titlecase' => $systemPath . 'Filter/Titlecase.php',
	'tx_form_system_filter_trim' => $systemPath . 'Filter/Trim.php',
	'tx_form_system_filter_uppercase' => $systemPath . 'Filter/Uppercase.php',

	'tx_form_system_layout' => $systemPath . 'Layout/Layout.php',
	'tx_form_system_loader' => $systemPath . 'Loader/Loader.php',
	'tx_form_system_localization' => $systemPath . 'Localization/Localization.php',

	'tx_form_system_postprocessor' => $systemPath . 'Postprocessor/Postprocessor.php',
	'tx_form_system_postprocessor_mail' => $systemPath . 'Postprocessor/Mail.php',

	'tx_form_system_request' => $systemPath . 'Request/Request.php',

	'tx_form_system_validate_abstract' => $systemPath . 'Validate/Abstract.php',
	'tx_form_system_validate_alphabetic' => $systemPath . 'Validate/Alphabetic.php',
	'tx_form_system_validate_alphanumeric' => $systemPath . 'Validate/Alphanumeric.php',
	'tx_form_system_validate_between' => $systemPath . 'Validate/Between.php',
	'tx_form_system_validate_captcha' => $systemPath . 'Validate/Captcha.php',
	'tx_form_system_validate_date' => $systemPath . 'Validate/Date.php',
	'tx_form_system_validate_digit' => $systemPath . 'Validate/Digit.php',
	'tx_form_system_validate_email' => $systemPath . 'Validate/Email.php',
	'tx_form_system_validate_equals' => $systemPath . 'Validate/Equals.php',
	'tx_form_system_validate_fileallowedtypes' => $systemPath . 'Validate/Fileallowedtypes.php',
	'tx_form_system_validate_fileminimumsize' => $systemPath . 'Validate/Fileminimumsize.php',
	'tx_form_system_validate_filemaximumsize' => $systemPath . 'Validate/Filemaximumsize.php',
	'tx_form_system_validate_float' => $systemPath . 'Validate/Float.php',
	'tx_form_system_validate_greaterthan' => $systemPath . 'Validate/Greaterthan.php',
	'tx_form_system_validate_inarray' => $systemPath . 'Validate/Inarray.php',
	'tx_form_system_validate_integer' => $systemPath . 'Validate/Integer.php',
	'tx_form_system_validate_interface' => $systemPath . 'Validate/Interface.php',
	'tx_form_system_validate_ip' => $systemPath . 'Validate/Ip.php',
	'tx_form_system_validate_length' => $systemPath . 'Validate/Length.php',
	'tx_form_system_validate_lessthan' => $systemPath . 'Validate/Lessthan.php',
	'tx_form_system_validate_regexp' => $systemPath . 'Validate/Regexp.php',
	'tx_form_system_validate_required' => $systemPath . 'Validate/Required.php',
	'tx_form_system_validate_uri' => $systemPath . 'Validate/Uri.php',
	'tx_form_system_validate' => $systemPath . 'Validate/Validate.php',

	'tx_form_view_confirmation' => $viewPath . 'Confirmation/Confirmation.php',

	'tx_form_view_confirmation_additional' => $viewPath . 'Confirmation/Additional/Additional.php',
	'tx_form_view_confirmation_additional_label' => $viewPath . 'Confirmation/Additional/Label.php',
	'tx_form_view_confirmation_additional_legend' => $viewPath . 'Confirmation/Additional/Legend.php',

	'tx_form_view_confirmation_element_abstract' => $viewPath . 'Confirmation/Element/Abstract.php',
	'tx_form_view_confirmation_element_checkboxgroup' => $viewPath . 'Confirmation/Element/Checkboxgroup.php',
	'tx_form_view_confirmation_element_checkbox' => $viewPath . 'Confirmation/Element/Checkbox.php',
	'tx_form_view_confirmation_element_container' => $viewPath . 'Confirmation/Element/Container.php',
	'tx_form_view_confirmation_element_fieldset' => $viewPath . 'Confirmation/Element/Fieldset.php',
	'tx_form_view_confirmation_element_fileupload' => $viewPath . 'Confirmation/Element/Fileupload.php',
	'tx_form_view_confirmation_element_optgroup' => $viewPath . 'Confirmation/Element/Optgroup.php',
	'tx_form_view_confirmation_element_option' => $viewPath . 'Confirmation/Element/Option.php',
	'tx_form_view_confirmation_element_radiogroup' => $viewPath . 'Confirmation/Element/Radiogroup.php',
	'tx_form_view_confirmation_element_radio' => $viewPath . 'Confirmation/Element/Radio.php',
	'tx_form_view_confirmation_element_select' => $viewPath . 'Confirmation/Element/Select.php',
	'tx_form_view_confirmation_element_textarea' => $viewPath . 'Confirmation/Element/Textarea.php',
	'tx_form_view_confirmation_element_textline' => $viewPath . 'Confirmation/Element/Textline.php',

	'tx_form_view_form' => $viewPath . 'Form/Form.php',

	'tx_form_view_form_additional' => $viewPath . 'Form/Additional/Additional.php',
	'tx_form_view_form_additional_error' => $viewPath . 'Form/Additional/Error.php',
	'tx_form_view_form_additional_label' => $viewPath . 'Form/Additional/Label.php',
	'tx_form_view_form_additional_legend' => $viewPath . 'Form/Additional/Legend.php',
	'tx_form_view_form_additional_mandatory' => $viewPath . 'Form/Additional/Mandatory.php',

	'tx_form_view_form_element_abstract' => $viewPath . 'Form/Element/Abstract.php',
	'tx_form_view_form_element_button' => $viewPath . 'Form/Element/Button.php',
	'tx_form_view_form_element_captcha' => $viewPath . 'Form/Element/Captcha.php',
	'tx_form_view_form_element_checkbox' => $viewPath . 'Form/Element/Checkbox.php',
	'tx_form_view_form_element_checkboxgroup' => $viewPath . 'Form/Element/Checkboxgroup.php',
	'tx_form_view_form_element_container' => $viewPath . 'Form/Element/Container.php',
	'tx_form_view_form_element_content' => $viewPath . 'Form/Element/Content.php',
	'tx_form_view_form_element_fieldset' => $viewPath . 'Form/Element/Fieldset.php',
	'tx_form_view_form_element_fileupload' => $viewPath . 'Form/Element/Fileupload.php',
	'tx_form_view_form_element_hidden' => $viewPath . 'Form/Element/Hidden.php',
	'tx_form_view_form_element_imagebutton' => $viewPath . 'Form/Element/Imagebutton.php',
	'tx_form_view_form_element_optgroup' => $viewPath . 'Form/Element/Optgroup.php',
	'tx_form_view_form_element_option' => $viewPath . 'Form/Element/Option.php',
	'tx_form_view_form_element_password' => $viewPath . 'Form/Element/Password.php',
	'tx_form_view_form_element_radio' => $viewPath . 'Form/Element/Radio.php',
	'tx_form_view_form_element_radiogroup' => $viewPath . 'Form/Element/Radiogroup.php',
	'tx_form_view_form_element_reset' => $viewPath . 'Form/Element/Reset.php',
	'tx_form_view_form_element_select' => $viewPath . 'Form/Element/Select.php',
	'tx_form_view_form_element_submit' => $viewPath . 'Form/Element/Submit.php',
	'tx_form_view_form_element_textarea' => $viewPath . 'Form/Element/Textarea.php',
	'tx_form_view_form_element_textline' => $viewPath . 'Form/Element/Textline.php',

	'tx_form_view_mail' => $viewPath . 'Mail/Mail.php',
	'tx_form_view_mail_html' => $viewPath . 'Mail/Html/Html.php',

	'tx_form_view_mail_html_additional' => $viewPath . 'Mail/Html/Additional/Additional.php',
	'tx_form_view_mail_html_additional_label' => $viewPath . 'Mail/Html/Additional/Label.php',
	'tx_form_view_mail_html_additional_legend' => $viewPath . 'Mail/Html/Additional/Legend.php',

	'tx_form_view_mail_html_element_abstract' => $viewPath . 'Mail/Html/Element/Abstract.php',
	'tx_form_view_mail_html_element_checkbox' => $viewPath . 'Mail/Html/Element/Checkbox.php',
	'tx_form_view_mail_html_element_checkboxgroup' => $viewPath . 'Mail/Html/Element/Checkboxgroup.php',
	'tx_form_view_mail_html_element_container' => $viewPath . 'Mail/Html/Element/Container.php',
	'tx_form_view_mail_html_element_fieldset' => $viewPath . 'Mail/Html/Element/Fieldset.php',
	'tx_form_view_mail_html_element_fileupload' => $viewPath . 'Mail/Html/Element/Fileupload.php',
	'tx_form_view_mail_html_element_hidden' => $viewPath . 'Mail/Html/Element/Hidden.php',
	'tx_form_view_mail_html_element_optgroup' => $viewPath . 'Mail/Html/Element/Optgroup.php',
	'tx_form_view_mail_html_element_option' => $viewPath . 'Mail/Html/Element/Option.php',
	'tx_form_view_mail_html_element_radio' => $viewPath . 'Mail/Html/Element/Radio.php',
	'tx_form_view_mail_html_element_radiogroup' => $viewPath . 'Mail/Html/Element/Radiogroup.php',
	'tx_form_view_mail_html_element_select' => $viewPath . 'Mail/Html/Element/Select.php',
	'tx_form_view_mail_html_element_textarea' => $viewPath . 'Mail/Html/Element/Textarea.php',
	'tx_form_view_mail_html_element_textline' => $viewPath . 'Mail/Html/Element/Textline.php',

	'tx_form_view_mail_plain' => $viewPath . 'Mail/Plain/Plain.php',
	'tx_form_view_mail_plain_element' => $viewPath . 'Mail/Plain/Element/Element.php',
	'tx_form_view_mail_plain_element_checkbox' => $viewPath . 'Mail/Plain/Element/Checkbox.php',
	'tx_form_view_mail_plain_element_checkboxgroup' => $viewPath . 'Mail/Plain/Element/Checkboxgroup.php',
	'tx_form_view_mail_plain_element_container' => $viewPath . 'Mail/Plain/Element/Container.php',
	'tx_form_view_mail_plain_element_fieldset' => $viewPath . 'Mail/Plain/Element/Fieldset.php',
	'tx_form_view_mail_plain_element_hidden' => $viewPath . 'Mail/Plain/Element/Hidden.php',
	'tx_form_view_mail_plain_element_optgroup' => $viewPath . 'Mail/Plain/Element/Optgroup.php',
	'tx_form_view_mail_plain_element_option' => $viewPath . 'Mail/Plain/Element/Option.php',
	'tx_form_view_mail_plain_element_radio' => $viewPath . 'Mail/Plain/Element/Radio.php',
	'tx_form_view_mail_plain_element_radiogroup' => $viewPath . 'Mail/Plain/Element/Radiogroup.php',
	'tx_form_view_mail_plain_element_select' => $viewPath . 'Mail/Plain/Element/Select.php',
	'tx_form_view_mail_plain_element_textarea' => $viewPath . 'Mail/Plain/Element/Textarea.php',
	'tx_form_view_mail_plain_element_textline' => $viewPath . 'Mail/Plain/Element/Textline.php',

	'tx_form_view_wizard_load' => $viewPath . 'Wizard/Load.php',
	'tx_form_view_wizard_save' => $viewPath . 'Wizard/Save.php',
	'tx_form_view_wizard_wizard' => $viewPath . 'Wizard/Wizard.php'
);
?>
