<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2011-09-20 16:43
$extensionClassesPath = \TYPO3\CMS\Core\Utility\ExtensionManagementUtility::extPath('form') . 'Classes/';
return array(
	'tx_form_controller_wizard' => $extensionClassesPath . 'Controller/Wizard.php',
);
