<?php
/**
 * Language labels for plugin FindReplace of htmlArea RTE (extension: rtehtmlarea)
 * 
 * This file is detected by the translation tool.
 */

$LOCAL_LANG = Array (
	'default' => Array (
		'Substitute this occurrence?' => 'Substitute this occurrence?',
		'Enter the text you want to find' => 'Enter the text you want to find',
		'Inform a replacement word' => 'This will erase all occurrences.',
		'found items' => 'found items',
		'replaced items' => 'replaced items',
		'found item' => 'item found',
		'replaced item' => 'item replaced',
		'not found' => 'not found',
		'Find and Replace' => 'Find And Replace',
		'Options' => 'Options:',
		'Whole words only' => 'Whole words only',
		'Case sensitive search' => 'Case sensitive search',
		'Substitute all occurrences' => 'Substitute all occurrences',
		'Search for:' => 'Search for:',
		'Replace with:' => 'Replace with:',
		'Actions' => 'Actions:',
		'Clear' => 'Clear',
		'Highlight' => 'Highlight',
		'Undo' => 'Undo',
		'Next' => 'Next',
		'Done' => 'Done',
	),
	'dk' => Array (
		'Substitute this occurrence?' => 'Erstat denne forekomst?',
		'Enter the text you want to find' => 'Indtast den tekst du vil finde',
		'Inform a replacement word' => 'Dette vil slette alle forekomster.',
		'found items' => 'fundne',
		'replaced items' => 'erstattet',
		'found item' => 'fundet',
		'replaced item' => 'erstattet',
		'not found' => 'ikke fundet',
		'Find and Replace' => 'Sшg og Erstat',
		'Options' => 'Valg:',
		'Whole words only' => 'Kun hele ord',
		'Case sensitive search' => 'Forskel pе store og smе bogstaver',
		'Substitute all occurrences' => 'Erstat alle forekomster',
		'Search for:' => 'Sшg efter:',
		'Replace with:' => 'Erstat med:',
		'Actions' => 'Gшr dette:',
		'Clear' => 'Nulstil',
		'Highlight' => 'Synliggшr',
		'Undo' => 'Fortryd',
		'Next' => 'Nжste',
		'Done' => 'Fжrdig',
	),
	'de' => Array (
		'Substitute this occurrence?' => 'Diesen Eintrag дndern?',
		'Enter the text you want to find' => 'Geben Sie den Suchtext ein',
		'Inform a replacement word' => 'Dies wird alle Vorkommnisse lцschen.',
		'found items' => 'gefundene',
		'replaced items' => 'ersetzte Eintrдge',
		'found item' => 'Eintrag gefunden',
		'replaced item' => 'Eintrag ersetzt',
		'not found' => 'nicht gefunden',
		'Find and Replace' => 'Suchen und Ersetzen',
		'Options' => 'Optionen:',
		'Whole words only' => 'Nur ganze Wцrter',
		'Case sensitive search' => 'GroЯ- und Kleinschreibung beachten',
		'Substitute all occurrences' => 'Alle Fundstellen ersetzen',
		'Search for:' => 'Suche nach:',
		'Replace with:' => 'Ersetze durch:',
		'Actions' => 'Aktionen:',
		'Clear' => 'Lцschen',
		'Highlight' => 'Hervorheben',
		'Undo' => 'Rьckgдngig',
		'Next' => 'Nдchster',
		'Done' => 'Fertig',
	),
	'no' => Array (
		'Substitute this occurrence?' => 'Bytt ut denne forekomsten?',
		'Enter the text you want to find' => 'Skriv inn teksten du шnsker е finne',
		'Inform a replacement word' => 'Dette vil slette alle forekomster.',
		'found items' => 'funnet',
		'replaced items' => 'byttet ut',
		'found item' => 'funnet',
		'replaced item' => 'byttet ut',
		'not found' => 'ikke funnet',
		'Find and Replace' => 'Sшk og erstatt',
		'Options' => 'Valg:',
		'Whole words only' => 'Bare hele ord',
		'Case sensitive search' => 'Skill mellom store og smе bokstaver',
		'Substitute all occurrences' => 'Bytt ut alle forekomster',
		'Search for:' => 'Sшk etter:',
		'Replace with:' => 'Bytt ut med:',
		'Actions' => 'Gjшr dette:',
		'Clear' => 'Tшm',
		'Highlight' => 'Synliggjшr',
		'Undo' => 'Gjшr om',
		'Next' => 'Neste',
		'Done' => 'Ferdig',
	),
	'it' => Array (
		'Substitute this occurrence?' => 'Sostituire questa occorrenza?',
		'Enter the text you want to find' => 'Inserisci il testo che vuoi trovare',
		'Inform a replacement word' => 'Questo cancellerа tutte le occorrenze.',
		'found items' => 'elementi trovati',
		'replaced items' => 'elementi sostituiti',
		'found item' => 'elemento trovato',
		'replaced item' => 'elemento sostituito',
		'not found' => 'non trovato',
		'Find and Replace' => 'Trova e Sostituisci',
		'Options' => 'Opzioni:',
		'Whole words only' => 'Solo parole intere',
		'Case sensitive search' => 'Ricerca sensibile a MAIUSCOLE/MINUSCOLE',
		'Substitute all occurrences' => 'Sostituisci tutte le occorrenze',
		'Search for:' => 'Cerca per:',
		'Replace with:' => 'Sostituisci con:',
		'Actions' => 'Azioni:',
		'Clear' => 'Pulisci',
		'Highlight' => 'Evidenzia',
		'Undo' => 'Passo indietro',
		'Next' => 'Prossima',
		'Done' => 'Fatto',
	),
	'fr' => Array (
		'Substitute this occurrence?' => 'Remplacer cette occurrence?',
		'Enter the text you want to find' => 'Йcrivez le texte que vous dйsirez rechercher',
		'Inform a replacement word' => 'Ceci effacera toutes les occurrences.',
		'found items' => 'occurrences trouvйes',
		'replaced items' => 'occurrences remplacйes',
		'found item' => 'occurrence trouvйe',
		'replaced item' => 'occurrence remplacйe',
		'not found' => 'n\'a pas йtй trouvй',
		'Find and Replace' => 'Rechercher et remplacer',
		'Options' => 'Options:',
		'Whole words only' => 'Mot entier uniquement',
		'Case sensitive search' => 'Respecter la casse',
		'Substitute all occurrences' => 'Remplacer tout',
		'Search for:' => 'Texte а rechercher:',
		'Replace with:' => 'Remplacer par:',
		'Actions' => 'Actions:',
		'Clear' => 'Normal',
		'Highlight' => 'En йvidence',
		'Undo' => 'Dйfaire',
		'Next' => 'Suivant',
		'Done' => 'Terminй',
	),
	'es' => Array (
		'Substitute this occurrence?' => 'їReemplazar este нtem?',
		'Enter the text you want to find' => 'Escriba el texto que desea buscar',
		'Inform a replacement word' => 'Esto borrarб todos los нtemes.',
		'found items' => 'нtemes localizados',
		'replaced items' => 'нtemes reemplazados',
		'found item' => 'нtem localizado',
		'replaced item' => 'нtem reemplazado',
		'not found' => 'no se encontrу',
		'Find and Replace' => 'Buscar y reemplazar',
		'Options' => 'Opciones:',
		'Whole words only' => 'Solo palabra completa',
		'Case sensitive search' => 'Coincidencia de mayъsculas/minъsculas',
		'Substitute all occurrences' => 'Reemplazar todo',
		'Search for:' => 'Encontrar texto:',
		'Replace with:' => 'Reemplazar con:',
		'Clear' => 'Limpiar',
		'Highlight' => 'Marcar',
		'Undo' => 'Deshacer',
		'Next' => 'Siguiente',
		'Done' => 'Finalizado',
	),
	'nl' => Array (
		'Substitute this occurrence?' => 'Vervang gevonden item?',
		'Enter the text you want to find' => 'Voer de tekst in die u wilt zoeken',
		'Inform a replacement word' => 'Dit verwijderd alle gevonden items.',
		'found items' => 'gevonden items',
		'replaced items' => 'vervangen items',
		'found item' => 'item gevonden',
		'replaced item' => 'item vervangen',
		'not found' => 'niet gevonden',
		'Find and Replace' => 'Zoeken en vervangen',
		'Options' => 'Opties:',
		'Whole words only' => 'Alleen hele woorden',
		'Case sensitive search' => 'Identieke hoofdletter/kleine letters',
		'Substitute all occurrences' => 'Alles vervangen',
		'Search for:' => 'Zoeken naar:',
		'Replace with:' => 'Vervangen door:',
		'Actions' => 'Acties:',
		'Clear' => 'Wissen',
		'Highlight' => 'Markeren',
		'Undo' => 'Ongedaan maken',
		'Next' => 'Volgende',
		'Done' => 'Klaar',
	),
	'cz' => Array (
	),
	'pl' => Array (
	),
	'si' => Array (
	),
	'fi' => Array (
		'Substitute this occurrence?' => 'Korvaa tдmд?',
		'Enter the text you want to find' => 'Anna teksti jonka haluat lцytдд',
		'Inform a replacement word' => 'Tдmд poistaa kaikki lцydetyt.',
		'found items' => 'haettuja lцydettiin',
		'replaced items' => 'korvattiin',
		'found item' => 'haettav lцydettiin',
		'replaced item' => 'haettava korvattiin',
		'not found' => 'ei lцytynyt',
		'Find and Replace' => 'Etsi ja Korvaa',
		'Options' => 'Vaihtoehdot:',
		'Whole words only' => 'Ainoastaan kokonaiset sanat',
		'Case sensitive search' => 'Isot/pienet riippuvainen haku',
		'Substitute all occurrences' => 'Korvaa kaikki lцydetyt',
		'Search for:' => 'Etsi:',
		'Replace with:' => 'Korvaa:',
		'Actions' => 'Toiminnot:',
		'Clear' => 'Tyhjдд',
		'Highlight' => 'Korosta',
		'Undo' => 'Palauta',
		'Next' => 'Seuraava',
		'Done' => 'Tehty',
	),
	'tr' => Array (
	),
	'se' => Array (
	),
	'pt' => Array (
	),
	'ru' => Array (
		'Substitute this occurrence?' => 'Заменить этот фрагмент?',
		'Enter the text you want to find' => 'Введите текст, который Вы хотите найти',
		'Inform a replacement word' => 'Это удалит все вхождения.',
		'found items' => 'найдено',
		'replaced items' => 'заменено',
		'found item' => 'эелемент найден',
		'replaced item' => 'элемент заменён',
		'not found' => 'не найден',
		'Find and Replace' => 'Найти и заменить',
		'Options' => 'Возможности:',
		'Whole words only' => 'Только слова полностью',
		'Case sensitive search' => 'Учитывать регистр (большие/маленькие буквы)',
		'Substitute all occurrences' => 'Заменить все фрагменты',
		'Search for:' => 'Искать:',
		'Replace with:' => 'Заменить на:',
		'Actions' => 'Действия:',
		'Clear' => 'Очистить',
		'Highlight' => 'Выделить',
		'Undo' => 'Вернуть',
		'Next' => 'Следующее',
		'Done' => 'Конец',
	),
	'ro' => Array (
	),
	'ch' => Array (
	),
	'sk' => Array (
		'Substitute this occurrence?' => 'Nahradiќ tento vэskyt?',
		'Enter the text you want to find' => 'Zadajte text, ktorэ chcete nбjsќ',
		'Inform a replacement word' => 'Toto vymaћe vљetky vэskyty.',
		'found items' => 'nбjdenэch poloћiek',
		'replaced items' => 'nahradenэch poloћiek',
		'found item' => 'nбjdenб poloћka',
		'replaced item' => 'nahradenб poloћka',
		'not found' => 'nenбjdenй',
		'Find and Replace' => 'Nбjsќ a nahradiќ',
		'Options' => 'Moћnosti:',
		'Whole words only' => 'Iba celй slovб',
		'Case sensitive search' => 'Rozliљovaќ veѕkй a malй pнsmenб',
		'Substitute all occurrences' => 'Nahradiќ vљetky vэskyty',
		'Search for:' => 'Hѕadaќ:',
		'Replace with:' => 'Nahradiќ:',
		'Actions' => 'Akcie:',
		'Clear' => 'Vyиistiќ',
		'Highlight' => 'Zvэrazniќ',
		'Undo' => 'Spдќ',
		'Next' => 'Dopredu',
		'Done' => 'Hotovo',
	),
	'lt' => Array (
	),
	'is' => Array (
	),
	'hr' => Array (
	),
	'hu' => Array (
	),
	'gl' => Array (
	),
	'th' => Array (
	),
	'gr' => Array (
	),
	'hk' => Array (
	),
	'eu' => Array (
	),
	'bg' => Array (
	),
	'br' => Array (
		'Substitute this occurrence?' => 'Substituir essa ocorrкncia?',
		'Enter the text you want to find' => 'Insira o texto que vocк quer encontrar',
		'Inform a replacement word' => 'Isso excluirб todas as ocorrкncias.',
		'found items' => 'itens encontrados',
		'replaced items' => 'itens substituнdos',
		'found item' => 'item encontrado',
		'replaced item' => 'item substituнdo',
		'not found' => 'nгo encontrado',
		'Find and Replace' => 'Localizar e Substituir',
		'Options' => 'Opзхes:',
		'Whole words only' => 'Palavras inteiras apenas',
		'Case sensitive search' => 'Localizaзгo sensнvel a caixa',
		'Substitute all occurrences' => 'Substituir todas as ocorrкncias',
		'Search for:' => 'Procurar por:',
		'Replace with:' => 'Substituir com:',
		'Actions' => 'Aзхes:',
		'Clear' => 'Limpar',
		'Highlight' => 'Destacar',
		'Undo' => 'Voltar',
		'Next' => 'Prуximo',
		'Done' => 'Finalizado',
	),
	'et' => Array (
	),
	'ar' => Array (
	),
	'he' => Array (
	),
	'ua' => Array (
	),
	'lv' => Array (
	),
	'jp' => Array (
	),
	'vn' => Array (
	),
	'ca' => Array (
	),
	'ba' => Array (
	),
	'kr' => Array (
	),
	'eo' => Array (
	),
	'my' => Array (
	),
	'hi' => Array (
	),
);
?>