<?php
return array(
	'Tx_Install_Interfaces_CheckTheDatabaseHook' => 'TYPO3\\CMS\\Install\\CheckTheDatabaseHookInterface',
	'tx_install_mod1' => 'TYPO3\\CMS\\Install\\Controller\\InstallToolModuleController',
	'tx_coreupdates_addflexformstoacl' => 'TYPO3\\CMS\\Install\\CoreUpdates\\AddFlexFormsToAclUpdate',
	'tx_coreupdates_charsetDefaults' => 'TYPO3\\CMS\\Install\\CoreUpdates\\CharsetDefaultsUpdate',
	'tx_coreupdates_compatversion' => 'TYPO3\\CMS\\Install\\CoreUpdates\\CompatVersionUpdate',
	'tx_coreupdates_compressionlevel' => 'TYPO3\\CMS\\Install\\CoreUpdates\\CompressionLevelUpdate',
	'tx_coreupdates_cscsplit' => 'TYPO3\\CMS\\Install\\CoreUpdates\\CscSplitUpdate',
	'tx_coreupdates_flagsfromsprite' => 'TYPO3\\CMS\\Install\\CoreUpdates\\FlagsFromSpriteUpdate',
	'tx_coreupdates_imagecols' => 'TYPO3\\CMS\\Install\\CoreUpdates\\ImagecolsUpdate',
	'tx_coreupdates_imagelink' => 'TYPO3\\CMS\\Install\\CoreUpdates\\ImagelinkUpdate',
	'tx_coreupdates_installsysexts' => 'TYPO3\\CMS\\Install\\CoreUpdates\\InstallSysExtsUpdate',
	'tx_coreupdates_mediaFlexform' => 'TYPO3\\CMS\\Install\\CoreUpdates\\MediaFlexformUpdate',
	'tx_coreupdates_mergeadvanced' => 'TYPO3\\CMS\\Install\\CoreUpdates\\MergeAdvancedUpdate',
	'tx_coreupdates_migrateworkspaces' => 'TYPO3\\CMS\\Install\\CoreUpdates\\MigrateWorkspacesUpdate',
	'tx_coreupdates_notinmenu' => 'TYPO3\\CMS\\Install\\CoreUpdates\\NotInMenuUpdate',
	'tx_coreupdates_t3skin' => 'TYPO3\\CMS\\Install\\CoreUpdates\\T3skinUpdate',
	'tx_install_ajax' => 'TYPO3\\CMS\\Install\\EidHandler',
	'Tx_Install_Service_BasicService' => 'TYPO3\\CMS\\Install\\EnableFileService',
	'tx_install' => 'TYPO3\\CMS\\Install\\Installer',
	'tx_install_report_InstallStatus' => 'TYPO3\\CMS\\Install\\Report\\InstallStatusReport',
	'tx_install_session' => 'TYPO3\\CMS\\Install\\Session',
	't3lib_install_Sql' => 'TYPO3\\CMS\\Install\\Sql\\SchemaMigrator',
	'Tx_Install_Updates_Base' => 'TYPO3\\CMS\\Install\\Updates\\AbstractUpdate',
	'Tx_Install_Updates_File_FilemountUpdateWizard' => 'TYPO3\\CMS\\Install\\Updates\\FilemountUpdateWizard',
	'Tx_Install_Updates_File_InitUpdateWizard' => 'TYPO3\\CMS\\Install\\Updates\\InitUpdateWizard',
	'Tx_Install_Updates_File_TceformsUpdateWizard' => 'TYPO3\\CMS\\Install\\Updates\\TceformsUpdateWizard',
	'Tx_Install_Updates_File_TtContentUploadsUpdateWizard' => 'TYPO3\\CMS\\Install\\Updates\\TtContentUploadsUpdateWizard',
);
?>