services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  TYPO3\CMS\FrontendLogin\:
    resource: '../Classes/*'

  feloginPasswordRecovery.rateLimiterFactory:
    class: Symfony\Component\RateLimiter\RateLimiterFactory
    arguments:
      $config:
        id: 'felogin-password-recovery'
        policy: 'sliding_window'
        limit: 5
        interval: '15 minutes'
      $storage: '@TYPO3\CMS\Core\RateLimiter\Storage\CachingFrameworkStorage'

  TYPO3\CMS\FrontendLogin\Controller\PasswordRecoveryController:
    arguments:
      $rateLimiterFactory: '@feloginPasswordRecovery.rateLimiterFactory'
