<?php

$LOCAL_LANG = Array (
	'default' => Array (
		'sys_note' => 'Internal note',
		'sys_note.category.I.1' => 'Instructions',
		'sys_note.category.I.2' => 'Notes',
		'sys_note.category.I.3' => 'To-do',
		'sys_note.category.I.4' => 'Template',
		'sys_note.subject' => 'Subject:',
		'sys_note.message' => 'Message:',
		'sys_note.personal' => 'Personal:',
	),
	'dk' => Array (
		'sys_note' => 'Intern note',
		'sys_note.category.I.1' => 'Vejledning',
		'sys_note.category.I.2' => 'Noter',
		'sys_note.category.I.3' => 'To-do',
		'sys_note.category.I.4' => 'Skabelon',
		'sys_note.subject' => 'Emne:',
		'sys_note.message' => 'Indhold:',
		'sys_note.personal' => 'Personlig:',
	),
	'de' => Array (
		'sys_note' => 'Interne Notiz',
		'sys_note.category.I.1' => 'Anweisung',
		'sys_note.category.I.2' => 'Notiz',
		'sys_note.category.I.3' => 'To-do',
		'sys_note.category.I.4' => 'Template',
		'sys_note.subject' => 'Titel:',
		'sys_note.message' => 'Inhalt:',
		'sys_note.personal' => 'Persцnlich:',
	),
	'no' => Array (
		'sys_note' => 'Internt notis',
		'sys_note.category.I.1' => 'Veiledning',
		'sys_note.category.I.2' => 'Notis',
		'sys_note.category.I.3' => 'Oppgave',
		'sys_note.category.I.4' => 'Mal',
		'sys_note.subject' => 'Emne:',
		'sys_note.message' => 'Innhold:',
		'sys_note.personal' => 'Personlig:',
	),
	'it' => Array (
		'sys_note' => 'Note interne',
		'sys_note.category.I.1' => 'Istruzioni',
		'sys_note.category.I.2' => 'Note',
		'sys_note.category.I.3' => 'To-do',
		'sys_note.category.I.4' => 'Template',
		'sys_note.subject' => 'Oggetto:',
		'sys_note.message' => 'Messaggio:',
		'sys_note.personal' => 'Personale:',
	),
	'fr' => Array (
		'sys_note' => 'Note interne',
		'sys_note.category.I.1' => 'Insctructions',
		'sys_note.category.I.2' => 'Notes',
		'sys_note.category.I.3' => 'A Faire',
		'sys_note.category.I.4' => 'Gabarit',
		'sys_note.subject' => 'Sujet:',
		'sys_note.message' => 'Message:',
		'sys_note.personal' => 'Personnel:',
	),
	'es' => Array (
		'sys_note' => 'Nota Interna',
		'sys_note.category.I.1' => 'Instructies',
		'sys_note.category.I.2' => 'Notas',
		'sys_note.category.I.3' => 'Por hacer',
		'sys_note.subject' => 'Asunto:',
		'sys_note.message' => 'Mensaje:',
		'sys_note.personal' => 'Personal:',
	),
	'nl' => Array (
		'sys_note' => 'Interne opmerking',
		'sys_note.category.I.1' => 'Instructies',
		'sys_note.category.I.2' => 'Opmerkingen',
		'sys_note.category.I.3' => 'Te-Doen',
		'sys_note.category.I.4' => 'Template',
		'sys_note.subject' => 'Onderwerp:',
		'sys_note.message' => 'Bericht:',
		'sys_note.personal' => 'Persoonlijk:',
	),
	'cz' => Array (
		'sys_note' => 'Internн poznбmka',
		'sys_note.category.I.1' => 'Instrukce',
		'sys_note.category.I.2' => 'Poznбmky',
		'sys_note.category.I.3' => 'Ъkoly',
		'sys_note.category.I.4' => 'Љablona',
		'sys_note.subject' => 'Pшedmмt:',
		'sys_note.message' => 'Zprбva:',
		'sys_note.personal' => 'Osobnн:',
	),
	'pl' => Array (
		'sys_note' => 'Notatka wewnкtrzna',
		'sys_note.category.I.1' => 'Instrukcja',
		'sys_note.category.I.2' => 'Notatka',
		'sys_note.category.I.3' => 'Do zrobienia',
		'sys_note.category.I.4' => 'Szablon',
		'sys_note.subject' => 'Temat:',
		'sys_note.message' => 'Wiadomo¶ж:',
		'sys_note.personal' => 'Skrуcona:',
	),
	'si' => Array (
		'sys_note' => 'Interna opomba',
		'sys_note.category.I.1' => 'Navodila',
		'sys_note.category.I.2' => 'Opombe',
		'sys_note.category.I.3' => 'Naloge',
		'sys_note.category.I.4' => 'Predloga',
		'sys_note.subject' => 'Predmet:',
		'sys_note.message' => 'Sporoиilo:',
		'sys_note.personal' => 'Osebno:',
	),
	'fi' => Array (
		'sys_note' => 'Sisдinen tiedote',
		'sys_note.category.I.1' => 'Ohjeet',
		'sys_note.category.I.2' => 'Muistiot',
		'sys_note.category.I.3' => 'To-Do',
		'sys_note.category.I.4' => 'Malli',
		'sys_note.subject' => 'Asia:',
		'sys_note.message' => 'Viesti:',
		'sys_note.personal' => 'Henkilцkohtainen:',
	),
	'tr' => Array (
		'sys_note' => 'Эз kэsma ait not',
		'sys_note.category.I.1' => 'Kэlavuz',
		'sys_note.category.I.2' => 'Notlar',
		'sys_note.category.I.3' => 'Yapэlacak iюler',
		'sys_note.category.I.4' => 'Юablon',
		'sys_note.subject' => 'Konu:',
		'sys_note.message' => 'Mesaj:',
		'sys_note.personal' => 'Kiюisel:',
	),
	'se' => Array (
		'sys_note' => 'Intern anmдrkning',
		'sys_note.category.I.1' => 'Instruktioner',
		'sys_note.category.I.2' => 'Anmдrkningar',
		'sys_note.category.I.3' => 'Att gцra',
		'sys_note.category.I.4' => 'Modell',
		'sys_note.subject' => 'Rubrik:',
		'sys_note.message' => 'Meddelande:',
		'sys_note.personal' => 'Personlig:',
	),
	'pt' => Array (
		'sys_note' => 'Nota interna',
		'sys_note.category.I.1' => 'Instruзхes',
		'sys_note.category.I.2' => 'Notas',
		'sys_note.category.I.3' => 'A-Fazer',
		'sys_note.category.I.4' => 'Modelo',
		'sys_note.subject' => 'Assunto:',
		'sys_note.message' => 'Mensagem:',
		'sys_note.personal' => 'Pessoal:',
	),
	'ru' => Array (
		'sys_note' => 'Служебная заметка',
		'sys_note.category.I.1' => 'Указания',
		'sys_note.category.I.2' => 'Заметки',
		'sys_note.category.I.3' => 'Инструкции',
		'sys_note.category.I.4' => 'Шаблон',
		'sys_note.subject' => 'Тема:',
		'sys_note.message' => 'Сообщение:',
		'sys_note.personal' => 'Личное:',
	),
	'ro' => Array (
		'sys_note' => 'Note interne',
		'sys_note.category.I.1' => 'Instructiuni',
		'sys_note.category.I.2' => 'Note',
		'sys_note.category.I.3' => 'De facut',
		'sys_note.category.I.4' => 'Sablon',
		'sys_note.subject' => 'Subiect',
		'sys_note.message' => 'Mesaj',
		'sys_note.personal' => 'Personal',
	),
	'ch' => Array (
	),
	'sk' => Array (
		'sys_note' => 'Internб poznбmka',
		'sys_note.category.I.1' => 'Inљtrukcie',
		'sys_note.category.I.2' => 'Poznбmky',
		'sys_note.category.I.3' => 'Ъlohy',
		'sys_note.category.I.4' => 'Љablona',
		'sys_note.subject' => 'Predmet :',
		'sys_note.message' => 'Sprбva :',
		'sys_note.personal' => 'Sъkromne :',
	),
	'lt' => Array (
	),
	'is' => Array (
	),
	'hr' => Array (
		'sys_note' => 'Interna napomena',
		'sys_note.category.I.1' => 'Instrukcije',
		'sys_note.category.I.2' => 'Napomene',
		'sys_note.category.I.3' => 'To-do',
		'sys_note.category.I.4' => 'Predloћak',
		'sys_note.subject' => 'Naslov:',
		'sys_note.message' => 'Poruka:',
		'sys_note.personal' => 'Osobno:',
	),
	'hu' => Array (
		'sys_note' => 'Belsх jegyzet',
		'sys_note.category.I.1' => 'Instrukciуk',
		'sys_note.category.I.2' => 'Jegyzet',
		'sys_note.category.I.3' => 'Tennivalу',
		'sys_note.category.I.4' => 'Sйma',
		'sys_note.subject' => 'Tбrgy',
		'sys_note.message' => 'Ьzenet',
		'sys_note.personal' => 'Szemйly',
	),
	'gl' => Array (
	),
	'th' => Array (
	),
	'gr' => Array (
	),
	'hk' => Array (
		'sys_note' => '¤єіЎµ§°O',
		'sys_note.category.I.1' => '«ь¤Ю',
		'sys_note.category.I.2' => 'µ§°O',
		'sys_note.category.I.3' => '­n°µЄє¤u§@',
		'sys_note.category.I.4' => 'јЛЄO',
		'sys_note.subject' => 'ҐDГDЎG',
		'sys_note.message' => '°T®§ЎG',
		'sys_note.personal' => '­У¤HЄєЎG',
	),
	'eu' => Array (
	),
	'bg' => Array (
		'sys_note' => 'Вътрешна бележка',
		'sys_note.category.I.1' => 'Инструкции',
		'sys_note.category.I.2' => 'Бележки',
		'sys_note.category.I.3' => 'За правене',
		'sys_note.category.I.4' => 'Шаблон',
		'sys_note.subject' => 'Относно:',
		'sys_note.message' => 'Съобщение:',
		'sys_note.personal' => 'Личен:',
	),
	'br' => Array (
		'sys_note' => 'Nota interna',
		'sys_note.category.I.1' => 'Instruзхes',
		'sys_note.category.I.2' => 'Anotaзхes',
		'sys_note.category.I.3' => 'A fazer',
		'sys_note.category.I.4' => 'Modelo',
		'sys_note.subject' => 'Assunto:',
		'sys_note.message' => 'Mensagem:',
		'sys_note.personal' => 'Pessoal:',
	),
	'et' => Array (
		'sys_note' => 'Sisemine mдrge',
		'sys_note.category.I.1' => 'Instruktsioonid',
		'sys_note.category.I.2' => 'Mдrkmed',
		'sys_note.category.I.3' => 'Ьlesanded',
		'sys_note.category.I.4' => 'Kujundusmall',
		'sys_note.subject' => 'Teema:',
		'sys_note.message' => 'Teade:',
		'sys_note.personal' => 'Personaalne:',
	),
	'ar' => Array (
	),
	'he' => Array (
	),
	'ua' => Array (
	),
	'lv' => Array (
	),
	'jp' => Array (
	),
	'vn' => Array (
	),
	'ca' => Array (
	),
	'ba' => Array (
	),
	'kr' => Array (
	),
);
?>