<?php

$LOCAL_LANG = Array (
	"default" => Array (
		"sys_note" => "Internal note",
		"sys_note.category.I.1" => "Instructions",
		"sys_note.category.I.2" => "Notes",
		"sys_note.category.I.3" => "To-do",
		"sys_note.category.I.4" => "Template",
		"sys_note.subject" => "Subject:",
		"sys_note.message" => "Message:",
		"sys_note.personal" => "Personal:",
	),
	"dk" => Array (
		"sys_note" => "Intern note",
		"sys_note.category.I.1" => "Vejledning",
		"sys_note.category.I.2" => "Noter",
		"sys_note.category.I.3" => "To-do",
		"sys_note.category.I.4" => "Skabelon",
		"sys_note.subject" => "Emne:",
		"sys_note.message" => "Indhold:",
		"sys_note.personal" => "Personlig:",
	),
	"de" => Array (
		"sys_note" => "Interne Notiz",
		"sys_note.category.I.1" => "Anweisung",
		"sys_note.category.I.2" => "Notiz",
		"sys_note.category.I.3" => "To-do",
		"sys_note.category.I.4" => "Template",
		"sys_note.subject" => "Titel:",
		"sys_note.message" => "Inhalt:",
		"sys_note.personal" => "Persönlich:",
	),
	"no" => Array (
		"sys_note" => "Internt notis",
		"sys_note.category.I.1" => "Veiledning",
		"sys_note.category.I.2" => "Notis",
		"sys_note.category.I.3" => "Oppgave",
		"sys_note.category.I.4" => "Mal",
		"sys_note.subject" => "Emne:",
		"sys_note.message" => "Innhold:",
		"sys_note.personal" => "Personlig:",
	),
	"it" => Array (
		"sys_note" => "Note interne",
		"sys_note.category.I.1" => "Istruzioni",
		"sys_note.category.I.2" => "Note",
		"sys_note.category.I.3" => "Da fare",
		"sys_note.category.I.4" => "Template",
		"sys_note.subject" => "Soggetto:",
		"sys_note.message" => "Messaggio:",
		"sys_note.personal" => "Personale:",
	),
	"fr" => Array (
		"sys_note" => "Note interne",
		"sys_note.category.I.1" => "Insctructions",
		"sys_note.category.I.2" => "Notes",
		"sys_note.category.I.3" => "A Faire",
		"sys_note.category.I.4" => "Gabarit",
		"sys_note.subject" => "Sujet:",
		"sys_note.message" => "Message:",
		"sys_note.personal" => "Personnel:",
	),
	"es" => Array (
		"sys_note" => "Nota Interna",
		"sys_note.category.I.1" => "Instructies",
		"sys_note.category.I.2" => "Notas",
		"sys_note.category.I.3" => "Por hacer",
		"sys_note.subject" => "Asunto:",
		"sys_note.message" => "Mensaje:",
		"sys_note.personal" => "Personal:",
	),
	"nl" => Array (
		"sys_note" => "Interne opmerking",
		"sys_note.category.I.1" => "Instructies",
		"sys_note.category.I.2" => "Opmerkingen",
		"sys_note.category.I.3" => "Te-Doen",
		"sys_note.category.I.4" => "Template",
		"sys_note.subject" => "Onderwerp:",
		"sys_note.message" => "Bericht:",
		"sys_note.personal" => "Persoonlijk:",
	),
	"cz" => Array (
		"sys_note" => "Interní poznámka",
		"sys_note.category.I.1" => "Instrukce",
		"sys_note.category.I.2" => "Poznámky",
		"sys_note.category.I.3" => "Úkoly",
		"sys_note.category.I.4" => "Šablona",
		"sys_note.subject" => "Pøedmìt:",
		"sys_note.message" => "Zpráva:",
		"sys_note.personal" => "Osobní:",
	),
	"pl" => Array (
		"sys_note" => "Notatka wewnêtrzna",
		"sys_note.category.I.1" => "Instrukcje",
		"sys_note.category.I.2" => "Notatki",
		"sys_note.category.I.3" => "Zadanie",
		"sys_note.category.I.4" => "Szablon",
		"sys_note.subject" => "Temat:",
		"sys_note.message" => "Wiadomo¶æ:",
		"sys_note.personal" => "Prywatna:",
	),
	"si" => Array (
		"sys_note" => "Interna opomba",
		"sys_note.category.I.1" => "Navodila",
		"sys_note.category.I.2" => "Opombe",
		"sys_note.category.I.3" => "Naloge",
		"sys_note.category.I.4" => "Predloga",
		"sys_note.subject" => "Predmet:",
		"sys_note.message" => "Sporoèilo:",
		"sys_note.personal" => "Osebno:",
	),
	"fi" => Array (
		"sys_note" => "Sisäinen tiedote",
		"sys_note.category.I.1" => "Ohjeet",
		"sys_note.category.I.2" => "Muistiot",
		"sys_note.category.I.3" => "To-Do",
		"sys_note.category.I.4" => "Malli",
		"sys_note.subject" => "Asia:",
		"sys_note.message" => "Viesti:",
		"sys_note.personal" => "Henkilökohtainen:",
	),
	"tr" => Array (
		"sys_note" => "Ýç kýsma ait not",
		"sys_note.category.I.1" => "Kýlavuz",
		"sys_note.category.I.2" => "Notlar",
		"sys_note.category.I.3" => "Yapýlacak iþler",
		"sys_note.category.I.4" => "Þablon",
		"sys_note.subject" => "Konu:",
		"sys_note.message" => "Mesaj:",
		"sys_note.personal" => "Kiþisel:",
	),
	"se" => Array (

	),
	"pt" => Array (

	),
	"ru" => Array (

	),
);
?>