<?php
return [
    'TYPO3\\CMS\\Lang\\LanguageService' => \TYPO3\CMS\Core\Localization\LanguageService::class,
    'TYPO3\\CMS\\ContextHelp\\Controller\\ContextHelpAjaxController' => \TYPO3\CMS\Backend\Controller\ContextHelpAjaxController::class,
    'TYPO3\\CMS\\Sv\\AbstractAuthenticationService' => \TYPO3\CMS\Core\Authentication\AbstractAuthenticationService::class,
    'TYPO3\\CMS\\Sv\\AuthenticationService' => \TYPO3\CMS\Core\Authentication\AuthenticationService::class,
    'TYPO3\\CMS\\Core\\IO\\PharStreamWrapper' => \TYPO3\PharStreamWrapper\PharStreamWrapper::class,
    'TYPO3\\CMS\\Core\\IO\\PharStreamWrapperException' => \TYPO3\PharStreamWrapper\Exception::class,
    'TYPO3\\CMS\\Core\\Tree\\TableConfiguration\\ExtJsArrayTreeRenderer' => \TYPO3\CMS\Core\Tree\TableConfiguration\ArrayTreeRenderer::class,
    'TYPO3\\CMS\\Core\\History\\RecordHistory' => \TYPO3\CMS\Core\DataHandling\History\RecordHistoryStore::class,
    'TYPO3\\CMS\\Saltedpasswords\\Salt\\AbstractSalt' => \TYPO3\CMS\Core\Crypto\PasswordHashing\AbstractComposedSalt::class,
    'TYPO3\\CMS\\Saltedpasswords\\Salt\\AbstractComposedSalt' => \TYPO3\CMS\Core\Crypto\PasswordHashing\AbstractComposedSalt::class,
    'TYPO3\\CMS\\Saltedpasswords\\Salt\\Argon2iSalt' => \TYPO3\CMS\Core\Crypto\PasswordHashing\Argon2iPasswordHash::class,
    'TYPO3\\CMS\\Saltedpasswords\\Salt\\BcryptSalt' => \TYPO3\CMS\Core\Crypto\PasswordHashing\BcryptPasswordHash::class,
    'TYPO3\\CMS\\Saltedpasswords\\Salt\\BlowfishSalt' => \TYPO3\CMS\Core\Crypto\PasswordHashing\BlowfishPasswordHash::class,
    'TYPO3\\CMS\\Saltedpasswords\\Salt\\ComposedSaltInterface' => \TYPO3\CMS\Core\Crypto\PasswordHashing\ComposedPasswordHashInterface::class,
    'TYPO3\\CMS\\Saltedpasswords\\Utility\\ExensionManagerConfigurationUtility' => \TYPO3\CMS\Core\Crypto\PasswordHashing\ExtensionManagerConfigurationUtility::class,
    'TYPO3\\CMS\\Saltedpasswords\\Exception\\InvalidSaltException' => \TYPO3\CMS\Core\Crypto\PasswordHashing\InvalidPasswordHashException::class,
    'TYPO3\\CMS\\Saltedpasswords\\Salt\\Md5Salt' => \TYPO3\CMS\Core\Crypto\PasswordHashing\Md5PasswordHash::class,
    'TYPO3\\CMS\\Saltedpasswords\\Salt\\SaltFactory' => \TYPO3\CMS\Core\Crypto\PasswordHashing\PasswordHashFactory::class,
    'TYPO3\\CMS\\Saltedpasswords\\Salt\\SaltInterface' => \TYPO3\CMS\Core\Crypto\PasswordHashing\PasswordHashInterface::class,
    'TYPO3\\CMS\\Saltedpasswords\\Salt\\Pbkdf2Salt' => \TYPO3\CMS\Core\Crypto\PasswordHashing\Pbkdf2PasswordHash::class,
    'TYPO3\\CMS\\Saltedpasswords\\Salt\\PhpassSalt' => \TYPO3\CMS\Core\Crypto\PasswordHashing\PhpassPasswordHash::class,
    'TYPO3\\CMS\\Saltedpasswords\\SaltedPasswordService' => \TYPO3\CMS\Core\Crypto\PasswordHashing\SaltedPasswordService::class,
    'TYPO3\\CMS\\Saltedpasswords\\Utility\\SaltedPasswordsUtility' => \TYPO3\CMS\Core\Crypto\PasswordHashing\SaltedPasswordsUtility::class,
];
