<?php

return [
    'dependencies' => [
        'backend',
    ],
    'imports' => [
        '@typo3/rte-ckeditor/' => [
            'path' => 'EXT:rte_ckeditor/Resources/Public/JavaScript/',
            'exclude' => [
                'EXT:core/Resources/Public/JavaScript/legacy/',
            ],
        ],
        '@typo3/ckeditor5/translations/' => 'EXT:rte_ckeditor/Resources/Public/Contrib/translations/',
        '@ckeditor/ckeditor5-alignment' => 'EXT:rte_ckeditor/Resources/Public/Contrib/@ckeditor/ckeditor5-alignment.js',
        '@ckeditor/ckeditor5-autoformat' => 'EXT:rte_ckeditor/Resources/Public/Contrib/@ckeditor/ckeditor5-autoformat.js',
        '@ckeditor/ckeditor5-basic-styles' => 'EXT:rte_ckeditor/Resources/Public/Contrib/@ckeditor/ckeditor5-basic-styles.js',
        '@ckeditor/ckeditor5-block-quote' => 'EXT:rte_ckeditor/Resources/Public/Contrib/@ckeditor/ckeditor5-block-quote.js',
        '@ckeditor/ckeditor5-clipboard' => 'EXT:rte_ckeditor/Resources/Public/Contrib/@ckeditor/ckeditor5-clipboard.js',
        '@ckeditor/ckeditor5-code-block' => 'EXT:rte_ckeditor/Resources/Public/Contrib/@ckeditor/ckeditor5-code-block.js',
        '@ckeditor/ckeditor5-core' => 'EXT:rte_ckeditor/Resources/Public/Contrib/@ckeditor/ckeditor5-core.js',
        '@ckeditor/ckeditor5-editor-classic' => 'EXT:rte_ckeditor/Resources/Public/Contrib/@ckeditor/ckeditor5-editor-classic.js',
        '@ckeditor/ckeditor5-editor-decoupled' => 'EXT:rte_ckeditor/Resources/Public/Contrib/@ckeditor/ckeditor5-editor-decoupled.js',
        '@ckeditor/ckeditor5-editor-multi-root' => 'EXT:rte_ckeditor/Resources/Public/Contrib/@ckeditor/ckeditor5-editor-multi-root.js',
        '@ckeditor/ckeditor5-engine' => 'EXT:rte_ckeditor/Resources/Public/Contrib/@ckeditor/ckeditor5-engine.js',
        '@ckeditor/ckeditor5-enter' => 'EXT:rte_ckeditor/Resources/Public/Contrib/@ckeditor/ckeditor5-enter.js',
        '@ckeditor/ckeditor5-essentials' => 'EXT:rte_ckeditor/Resources/Public/Contrib/@ckeditor/ckeditor5-essentials.js',
        '@ckeditor/ckeditor5-find-and-replace' => 'EXT:rte_ckeditor/Resources/Public/Contrib/@ckeditor/ckeditor5-find-and-replace.js',
        '@ckeditor/ckeditor5-font' => 'EXT:rte_ckeditor/Resources/Public/Contrib/@ckeditor/ckeditor5-font.js',
        '@ckeditor/ckeditor5-fullscreen' => 'EXT:rte_ckeditor/Resources/Public/Contrib/@ckeditor/ckeditor5-fullscreen.js',
        '@ckeditor/ckeditor5-heading' => 'EXT:rte_ckeditor/Resources/Public/Contrib/@ckeditor/ckeditor5-heading.js',
        '@ckeditor/ckeditor5-highlight' => 'EXT:rte_ckeditor/Resources/Public/Contrib/@ckeditor/ckeditor5-highlight.js',
        '@ckeditor/ckeditor5-horizontal-line' => 'EXT:rte_ckeditor/Resources/Public/Contrib/@ckeditor/ckeditor5-horizontal-line.js',
        '@ckeditor/ckeditor5-html-support' => 'EXT:rte_ckeditor/Resources/Public/Contrib/@ckeditor/ckeditor5-html-support.js',
        '@ckeditor/ckeditor5-icons' => 'EXT:rte_ckeditor/Resources/Public/Contrib/@ckeditor/ckeditor5-icons.js',
        '@ckeditor/ckeditor5-image' => 'EXT:rte_ckeditor/Resources/Public/Contrib/@ckeditor/ckeditor5-image.js',
        '@ckeditor/ckeditor5-indent' => 'EXT:rte_ckeditor/Resources/Public/Contrib/@ckeditor/ckeditor5-indent.js',
        '@ckeditor/ckeditor5-inspector' => 'EXT:rte_ckeditor/Resources/Public/Contrib/@ckeditor/ckeditor5-inspector.js',
        '@ckeditor/ckeditor5-language' => 'EXT:rte_ckeditor/Resources/Public/Contrib/@ckeditor/ckeditor5-language.js',
        '@ckeditor/ckeditor5-link' => 'EXT:rte_ckeditor/Resources/Public/Contrib/@ckeditor/ckeditor5-link.js',
        '@ckeditor/ckeditor5-list' => 'EXT:rte_ckeditor/Resources/Public/Contrib/@ckeditor/ckeditor5-list.js',
        '@ckeditor/ckeditor5-mention' => 'EXT:rte_ckeditor/Resources/Public/Contrib/@ckeditor/ckeditor5-mention.js',
        '@ckeditor/ckeditor5-paragraph' => 'EXT:rte_ckeditor/Resources/Public/Contrib/@ckeditor/ckeditor5-paragraph.js',
        '@ckeditor/ckeditor5-paste-from-office' => 'EXT:rte_ckeditor/Resources/Public/Contrib/@ckeditor/ckeditor5-paste-from-office.js',
        '@ckeditor/ckeditor5-remove-format' => 'EXT:rte_ckeditor/Resources/Public/Contrib/@ckeditor/ckeditor5-remove-format.js',
        '@ckeditor/ckeditor5-select-all' => 'EXT:rte_ckeditor/Resources/Public/Contrib/@ckeditor/ckeditor5-select-all.js',
        '@ckeditor/ckeditor5-show-blocks' => 'EXT:rte_ckeditor/Resources/Public/Contrib/@ckeditor/ckeditor5-show-blocks.js',
        '@ckeditor/ckeditor5-source-editing' => 'EXT:rte_ckeditor/Resources/Public/Contrib/@ckeditor/ckeditor5-source-editing.js',
        '@ckeditor/ckeditor5-special-characters' => 'EXT:rte_ckeditor/Resources/Public/Contrib/@ckeditor/ckeditor5-special-characters.js',
        '@ckeditor/ckeditor5-style' => 'EXT:rte_ckeditor/Resources/Public/Contrib/@ckeditor/ckeditor5-style.js',
        '@ckeditor/ckeditor5-table' => 'EXT:rte_ckeditor/Resources/Public/Contrib/@ckeditor/ckeditor5-table.js',
        '@ckeditor/ckeditor5-theme-lark' => 'EXT:rte_ckeditor/Resources/Public/Contrib/@ckeditor/ckeditor5-theme-lark.js',
        '@ckeditor/ckeditor5-typing' => 'EXT:rte_ckeditor/Resources/Public/Contrib/@ckeditor/ckeditor5-typing.js',
        '@ckeditor/ckeditor5-ui' => 'EXT:rte_ckeditor/Resources/Public/Contrib/@ckeditor/ckeditor5-ui.js',
        '@ckeditor/ckeditor5-undo' => 'EXT:rte_ckeditor/Resources/Public/Contrib/@ckeditor/ckeditor5-undo.js',
        '@ckeditor/ckeditor5-upload' => 'EXT:rte_ckeditor/Resources/Public/Contrib/@ckeditor/ckeditor5-upload.js',
        '@ckeditor/ckeditor5-utils' => 'EXT:rte_ckeditor/Resources/Public/Contrib/@ckeditor/ckeditor5-utils.js',
        '@ckeditor/ckeditor5-watchdog' => 'EXT:rte_ckeditor/Resources/Public/Contrib/@ckeditor/ckeditor5-watchdog.js',
        '@ckeditor/ckeditor5-widget' => 'EXT:rte_ckeditor/Resources/Public/Contrib/@ckeditor/ckeditor5-widget.js',
        '@ckeditor/ckeditor5-word-count' => 'EXT:rte_ckeditor/Resources/Public/Contrib/@ckeditor/ckeditor5-word-count.js',
        // Provided for backwards compatibility reasons
        '@typo3/ckeditor5-bundle.js' => 'EXT:rte_ckeditor/Resources/Public/JavaScript/legacy/ckeditor5-bundle.js',
        '@typo3/ckeditor5-inspector.js' => 'EXT:rte_ckeditor/Resources/Public/JavaScript/legacy/ckeditor5-inspector.js',
    ],
];
