<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2011-06-14 11:34

$extensionPath = t3lib_extMgm::extPath('lang');
$extensionClassesPath = t3lib_extMgm::extPath('lang') . 'classes/';
return array(
	'tx_lang_factory' => $extensionClassesPath . 'class.tx_lang_factory.php',
	'tx_lang_store' => $extensionClassesPath . 'class.tx_lang_store.php',
	'tx_lang_cache_abstract' => $extensionClassesPath . 'cache/class.tx_lang_cache_abstract.php',
	'tx_lang_cache_cachingframework' => $extensionClassesPath . 'cache/class.tx_lang_cache_cachingframework.php',
	'tx_lang_cache_file' => $extensionClassesPath . 'cache/class.tx_lang_cache_file.php',
	'tx_lang_exception_filenotfound' => $extensionClassesPath . 'exception/class.tx_lang_exception_filenotfound.php',
	'tx_lang_exception_invalidparser' => $extensionClassesPath . 'exception/class.tx_lang_exception_invalidparser.php',
	'tx_lang_exception_invalidxmlfile' => $extensionClassesPath . 'exception/class.tx_lang_exception_invalidxmlfile.php',
	'tx_lang_parser' => $extensionClassesPath . 'interfaces/interface.tx_lang_parser.php',
	'tx_lang_parser_abstractxml' => $extensionClassesPath . 'parser/class.tx_lang_parser_abstractxml.php',
	'tx_lang_parser_llphp' => $extensionClassesPath . 'parser/class.tx_lang_parser_llphp.php',
	'tx_lang_parser_llxml' => $extensionClassesPath . 'parser/class.tx_lang_parser_llxml.php',
	'tx_lang_parser_xliff' => $extensionClassesPath . 'parser/class.tx_lang_parser_xliff.php',
);
?>