<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2010-09-15 16:18

$extensionPath = t3lib_extMgm::extPath('workspaces');
return array(
	'tx_workspaces_service_stages' => $extensionPath . 'Classes/Service/Stages.php',
	'tx_workspaces_module_interface' => $extensionPath . 'Classes/Module/Interface.php',
	'tx_workspaces_module_abstract' => $extensionPath . 'Classes/Module/Abstract.php',
	'tx_workspaces_module_review' => $extensionPath . 'Classes/Module/Review.php',
	'tx_workspaces_service_workspaces' => $extensionPath . 'Classes/Service/Workspaces.php',
	'tx_workspaces_service_stages' => $extensionPath . 'Classes/Service/Stages.php',
	'tx_workspaces_module1' => $extensionPath . 'mod1/index.php',
	'tx_workspaces_service_griddata' => $extensionPath . 'Classes/Service/GridData.php',
	'tx_workspaces_service_autopublish' => $extensionPath . 'Classes/Service/AutoPublish.php',
	'tx_workspaces_service_autopublishtask' => $extensionPath . 'Classes/Service/AutoPublishTask.php',
	'tx_workspaces_service_tcemain' => $extensionPath . 'Classes/Service/Tcemain.php',
	'tx_workspaces_service_befunc' => $extensionPath . 'Classes/Service/Befunc.php',
	'tx_workspaces_extdirect_abstracthandler' => $extensionPath . 'Classes/ExtDirect/AbstractHandler.php',
	'tx_workspaces_controller_abstractcontroller' => $extensionPath . 'Classes/Controller/AbstractController.php',
	'tx_workspaces_controller_reviewcontroller' => $extensionPath . 'Classes/Controller/ReviewController.php',
	'tx_workspaces_controller_previewcontroller' => $extensionPath . 'Classes/Controller/PreviewController.php'
);
?>