<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2010-11-11 21:58
$extensionPath = \TYPO3\CMS\Core\Utility\ExtensionManagementUtility::extPath('workspaces');
return array(
	'tx_workspaces_controller_abstractcontroller' => $extensionPath . 'Classes/Controller/AbstractController.php',
	'tx_workspaces_controller_previewcontroller' => $extensionPath . 'Classes/Controller/PreviewController.php',
	'tx_workspaces_controller_reviewcontroller' => $extensionPath . 'Classes/Controller/ReviewController.php',
	'tx_workspaces_domain_model_combinedrecord' => $extensionPath . 'Classes/Domain/Model/CombinedRecord.php',
	'tx_workspaces_domain_model_databaserecord' => $extensionPath . 'Classes/Domain/Model/DatabaseRecord.php',
	'tx_workspaces_extdirect_abstracthandler' => $extensionPath . 'Classes/ExtDirect/AbstractHandler.php',
	'tx_workspaces_extdirect_actionhandler' => $extensionPath . 'Classes/ExtDirect/ActionHandler.php',
	'tx_workspaces_extdirect_massactionhandler' => $extensionPath . 'Classes/ExtDirect/MassActionHandler.php',
	'tx_workspaces_extdirect_server' => $extensionPath . 'Classes/ExtDirect/Server.php',
	'tx_workspaces_extdirect_toolbarmenu' => $extensionPath . 'Classes/ExtDirect/ToolbarMenu.php',
	'tx_workspaces_reports_statusprovider' => $extensionPath . 'Classes/Reports/StatusProvider.php',
	'tx_workspaces_service_autopublish' => $extensionPath . 'Classes/Service/AutoPublish.php',
	'tx_workspaces_service_autopublishtask' => $extensionPath . 'Classes/Service/AutoPublishTask.php',
	'tx_workspaces_service_cleanuppreviewlinktask' => $extensionPath . 'Classes/Service/CleanupPreviewLinkTask.php',
	'tx_workspaces_service_befunc' => $extensionPath . 'Classes/Service/Befunc.php',
	'tx_workspaces_service_griddata' => $extensionPath . 'Classes/Service/GridData.php',
	'tx_workspaces_service_history' => $extensionPath . 'Classes/Service/History.php',
	'tx_workspaces_service_integrity' => $extensionPath . 'Classes/Service/Integrity.php',
	'tx_workspaces_service_stages' => $extensionPath . 'Classes/Service/Stages.php',
	'tx_workspaces_service_tcemain' => $extensionPath . 'Classes/Service/Tcemain.php',
	'tx_workspaces_service_workspaces' => $extensionPath . 'Classes/Service/Workspaces.php',
	'tx_workspaces_service_workspacestest' => $extensionPath . 'Tests/Service/WorkspaceTest.php'
);
?>