/*
 * This file is part of the TYPO3 CMS project.
 *
 * It is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License, either version 2
 * of the License, or any later version.
 *
 * For the full copyright and license information, please read the
 * LICENSE.txt file that was distributed with this source code.
 *
 * The TYPO3 project - inspiring people to share!
 */
var __createBinding=this&&this.__createBinding||(Object.create?function(e,t,n,a){void 0===a&&(a=n),Object.defineProperty(e,a,{enumerable:!0,get:function(){return t[n]}})}:function(e,t,n,a){void 0===a&&(a=n),e[a]=t[n]}),__setModuleDefault=this&&this.__setModuleDefault||(Object.create?function(e,t){Object.defineProperty(e,"default",{enumerable:!0,value:t})}:function(e,t){e.default=t}),__importStar=this&&this.__importStar||function(e){if(e&&e.__esModule)return e;var t={};if(null!=e)for(var n in e)"default"!==n&&Object.prototype.hasOwnProperty.call(e,n)&&__createBinding(t,e,n);return __setModuleDefault(t,e),t};define(["require","exports","TYPO3/CMS/Backend/Element/ImmediateActionElement","TYPO3/CMS/Backend/ModuleMenu","TYPO3/CMS/Backend/Viewport"],(function(e,t,n,a,r){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),describe("TYPO3/CMS/Backend/Element/ImmediateActionElement:",()=>{let t;beforeEach(()=>{t=document.createElement("div"),document.body.appendChild(t)}),afterEach(()=>{t.remove(),t=null}),it("dispatches action when created via constructor",async()=>{const a=r.Topbar,i={refresh:()=>{}};spyOn(i,"refresh").and.callThrough(),r.Topbar=i;const o=new n.ImmediateActionElement;o.setAttribute("action","TYPO3.Backend.Topbar.refresh"),expect(i.refresh).not.toHaveBeenCalled(),t.appendChild(o),await new Promise((t,n)=>{e(["TYPO3/CMS/Backend/Viewport"],t,n)}).then(__importStar),await new Promise(e=>setTimeout(e,100)),expect(i.refresh).toHaveBeenCalled(),r.Topbar=a}),it("dispatches action when created via createElement",async()=>{const n=r.Topbar,a={refresh:()=>{}};spyOn(a,"refresh").and.callThrough(),r.Topbar=a;const i=document.createElement("typo3-immediate-action");i.setAttribute("action","TYPO3.Backend.Topbar.refresh"),expect(a.refresh).not.toHaveBeenCalled(),t.appendChild(i),await new Promise((t,n)=>{e(["TYPO3/CMS/Backend/Viewport"],t,n)}).then(__importStar),await new Promise(e=>setTimeout(e,100)),expect(a.refresh).toHaveBeenCalled(),r.Topbar=n}),it("dispatches action when created from string",async()=>{const n=a.App,i={refreshMenu:()=>{}};spyOn(i,"refreshMenu").and.callThrough(),a.App=i;const o=document.createRange().createContextualFragment('<typo3-immediate-action action="TYPO3.ModuleMenu.App.refreshMenu"></typo3-immediate-action>').querySelector("typo3-immediate-action");expect(i.refreshMenu).not.toHaveBeenCalled(),t.appendChild(o),await new Promise((t,n)=>{e(["TYPO3/CMS/Backend/ModuleMenu"],t,n)}).then(__importStar),await new Promise(e=>setTimeout(e,100)),expect(i.refreshMenu).toHaveBeenCalled(),r.App=n}),it("dispatches action when created via innerHTML",async()=>{const n=a.App,r={refreshMenu:()=>{}};spyOn(r,"refreshMenu").and.callThrough(),a.App=r,t.innerHTML='<typo3-immediate-action action="TYPO3.ModuleMenu.App.refreshMenu"></typo3-immediate-action>',await new Promise((t,n)=>{e(["TYPO3/CMS/Backend/ModuleMenu"],t,n)}).then(__importStar),await new Promise(e=>setTimeout(e,100)),expect(r.refreshMenu).toHaveBeenCalled(),a.App=n})})}));