<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2011-08-22 08:37
$extensionPath = \TYPO3\CMS\Core\Utility\ExtensionManagementUtility::extPath('rsaauth');
return array(
	'tx_rsaauth_sv1' => $extensionPath . 'sv1/class.tx_rsaauth_sv1.php',
);
?>