<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2011-08-22 08:37
$extensionPath = \TYPO3\CMS\Core\Utility\ExtensionManagementUtility::extPath('rsaauth');
return array(
	'tx_rsaauth_backendwarnings' => $extensionPath . 'hooks/class.tx_rsaauth_backendwarnings.php',
	'tx_rsaauth_feloginhook' => $extensionPath . 'hooks/class.tx_rsaauth_feloginhook.php',
	'tx_rsaauth_loginformhook' => $extensionPath . 'hooks/class.tx_rsaauth_loginformhook.php',
	'tx_rsaauth_sv1' => $extensionPath . 'sv1/class.tx_rsaauth_sv1.php',
	'tx_rsaauth_abstract_backend' => $extensionPath . 'sv1/backends/class.tx_rsaauth_abstract_backend.php',
	'tx_rsaauth_backendfactory' => $extensionPath . 'sv1/backends/class.tx_rsaauth_backendfactory.php',
	'tx_rsaauth_cmdline_backend' => $extensionPath . 'sv1/backends/class.tx_rsaauth_cmdline_backend.php',
	'tx_rsaauth_keypair' => $extensionPath . 'sv1/backends/class.tx_rsaauth_keypair.php',
	'tx_rsaauth_php_backend' => $extensionPath . 'sv1/backends/class.tx_rsaauth_php_backend.php',
	'tx_rsaauth_abstract_storage' => $extensionPath . 'sv1/storage/class.tx_rsaauth_abstract_storage.php',
	'tx_rsaauth_session_storage' => $extensionPath . 'sv1/storage/class.tx_rsaauth_session_storage.php',
	'tx_rsaauth_split_storage' => $extensionPath . 'sv1/storage/class.tx_rsaauth_split_storage.php',
	'tx_rsaauth_storagefactory' => $extensionPath . 'sv1/storage/class.tx_rsaauth_storagefactory.php'
);
?>