services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  TYPO3\CMS\Recordlist\:
    resource: '../Classes/*'

  TYPO3\CMS\Recordlist\Controller\RecordListController:
    tags: ['backend.controller']

  TYPO3\CMS\Recordlist\Controller\RecordDownloadController:
    tags: ['backend.controller']

  TYPO3\CMS\Recordlist\Controller\ElementBrowserController:
    tags: ['backend.controller']

  TYPO3\CMS\Recordlist\Browser\DatabaseBrowser:
    shared: false
    public: true

  TYPO3\CMS\Recordlist\Browser\FileBrowser:
    shared: false
    public: true

  TYPO3\CMS\Recordlist\Browser\FolderBrowser:
    shared: false
    public: true

  TYPO3\CMS\Recordlist\Browser\RecordBrowser:
    shared: false
    public: true

  TYPO3\CMS\Recordlist\RecordList\DatabaseRecordList:
    shared: false
    public: true

  TYPO3\CMS\Recordlist\HookProvider\AddToRecordListHookProvider:
    tags:
      - name: event.listener
        identifier: 'record-list-content-legacy-hook'
