<?php
/**
 * Language labels for extension "css_styled_content"
 * 
 * $Id$
 * 
 * This file is detected by the translation tool.
 */

$LOCAL_LANG = Array (
	'default' => Array (
		'label.toTop' => 'To top',
		'login.username' => 'Username:',
		'login.password' => 'Password:',
		'login.login' => 'Login',
		'login.logout' => 'Logout',
		'search.emptySearch' => 'Sorry, your search was empty!',
		'search.resultRange' => 'Searchresult: ###RANGELOW###-###RANGEHIGH### of ###TOTAL###',
		'search.searchResultNext' => 'Next',
		'search.searchResultPrev' => 'Prev',
		'search.searchWord' => 'Searchword:',
		'search.searchIn' => 'Search in:',
		'search.headersKeywords' => 'Headers and keywords',
		'search.pageContent' => 'Page content',
		'search.searchButton' => 'Search now!',
		'eIcon.html' => 'Edit pure HTML content',
		'eIcon.header' => 'Edit header',
		'eIcon.subheader' => 'Edit subheader',
		'eIcon.bodytext' => 'Edit bodytext',
		'eIcon.images' => 'Edit images',
		'eIcon.caption' => 'Edit image caption',
		'eIcon.bullets' => 'Edit bullet list',
		'eIcon.table' => 'Edit table',
		'eIcon.filelist' => 'Edit file list',
		'eIcon.menuSitemap' => 'Edit menu / sitemap',
		'eIcon.recordList' => 'Edit recordlist',
		'eIcon.plugin' => 'Change/configure plugin',
		'eIcon.multimedia' => 'Edit multimedia element',
		'eIcon.form' => 'Edit email form',
		'eIcon.search' => 'Edit search element',
		'eIcon.login' => 'Edit login element',
		'eIcon.page' => 'Page:',
	),
	'dk' => Array (
		'label.toTop' => 'Til toppen',
		'login.username' => 'Brugernavn:',
		'login.password' => 'Kodeord:',
		'login.login' => 'Login',
		'login.logout' => 'Logout',
		'search.emptySearch' => 'Beklager, men din søgning var tom!',
		'search.resultRange' => 'Søgeresultat: ###RANGELOW###-###RANGEHIGH### ud af ###TOTAL###',
		'search.searchResultNext' => 'Næste',
		'search.searchResultPrev' => 'Forrige',
		'search.searchWord' => 'Søgeord:',
		'search.searchIn' => 'Søg i:',
		'search.headersKeywords' => 'Overskrifter og nøgleord',
		'search.pageContent' => 'Sideindhold',
		'search.searchButton' => 'Søg nu!',
		'eIcon.html' => 'Rediger ren HTML',
		'eIcon.header' => 'Rediger overskrift',
		'eIcon.subheader' => 'Rediger manchet tekst',
		'eIcon.bodytext' => 'Rediger brødtekst',
		'eIcon.images' => 'Rediger billeder',
		'eIcon.caption' => 'Rediger billedtekst',
		'eIcon.bullets' => 'Rediger punktliste',
		'eIcon.table' => 'Rediger tabel',
		'eIcon.filelist' => 'Rediger filliste',
		'eIcon.menuSitemap' => 'Rediger menu/oversigtskort',
		'eIcon.recordList' => 'Rediger elementliste',
		'eIcon.plugin' => 'Ændre/Konfigurer plugin',
		'eIcon.multimedia' => 'Rediger multimedie element',
		'eIcon.form' => 'Rediger email formular',
		'eIcon.search' => 'Rediger søge formular',
		'eIcon.login' => 'Rediger login formular',
		'eIcon.page' => 'Side:',
	),
	'de' => Array (
		'label.toTop' => 'Nach oben',
		'login.username' => 'Benutzername:',
		'login.password' => 'Password:',
		'login.login' => 'Login',
		'login.logout' => 'Logout',
		'search.emptySearch' => 'Ihre Suche lieferte leider keine Ergebnisse.',
		'search.resultRange' => 'Suchergebnis: ###RANGELOW###-###RANGEHIGH### von ###TOTAL###',
		'search.searchResultNext' => 'Nächste',
		'search.searchResultPrev' => 'Vorherige',
		'search.searchWord' => 'Suchwort:',
		'search.searchIn' => 'Suchen in:',
		'search.headersKeywords' => 'Überschriften und Schlagwörter',
		'search.pageContent' => 'Seiteninhalt',
		'search.searchButton' => 'Suchen!',
		'eIcon.html' => 'Reinen HTML Inhalt bearbeiten',
		'eIcon.header' => 'Überschrift bearbeiten',
		'eIcon.subheader' => 'Unterüberschrift bearbeiten',
		'eIcon.bodytext' => 'Textkörper bearbeiten',
		'eIcon.images' => 'Bilder bearbeiten',
		'eIcon.caption' => 'Bildunterschrift bearbeiten',
		'eIcon.bullets' => 'Aufzählungsliste bearbeiten',
		'eIcon.table' => 'Tabelle bearbeiten',
		'eIcon.filelist' => 'Dateiliste bearbeiten',
		'eIcon.menuSitemap' => 'Menü/Sitemap bearbeiten',
		'eIcon.recordList' => 'Datensatz bearbeiten',
		'eIcon.plugin' => 'Plugin ändern/konfigurieren',
		'eIcon.multimedia' => 'Multimedia Element bearbeiten',
		'eIcon.form' => 'Email Formular bearbeiten',
		'eIcon.search' => 'Suchbox bearbeiten',
		'eIcon.login' => 'Login bearbeiten',
		'eIcon.page' => 'Seite:',
	),
	'no' => Array (
		'label.toTop' => 'Til toppen',
		'login.username' => 'Brukernavn:',
		'login.password' => 'Passord:',
		'login.login' => 'Logg inn',
		'login.logout' => 'Logg ut',
		'search.emptySearch' => 'Beklager, søket ga ingen resultater',
		'search.resultRange' => 'Søkeresultat: ###RANGELOW###-###RANGEHIGH### av ###TOTAL###',
		'search.searchResultNext' => 'Neste',
		'search.searchResultPrev' => 'Forrige',
		'search.searchWord' => 'Søkeord:',
		'search.searchIn' => 'Søk i:',
		'search.headersKeywords' => 'Overskrifter og nøkkelord',
		'search.pageContent' => 'Sideinnhold',
		'search.searchButton' => 'Søk',
		'eIcon.html' => 'Redigér ren HTML',
		'eIcon.header' => 'Redigér overskrift',
		'eIcon.subheader' => 'Redigér undertittel',
		'eIcon.bodytext' => 'Redigér brødtekst',
		'eIcon.images' => 'Redigér bilder',
		'eIcon.caption' => 'Redigér bildetekst',
		'eIcon.bullets' => 'Redigér punktliste',
		'eIcon.table' => 'Redigér tabell',
		'eIcon.filelist' => 'Redigér filliste',
		'eIcon.menuSitemap' => 'Redigér meny/sidekart',
		'eIcon.recordList' => 'Redigér elementliste',
		'eIcon.plugin' => 'Endre/konfigurer plugin',
		'eIcon.multimedia' => 'Redigér multimedia-element',
		'eIcon.form' => 'Redigér epost-skjema',
		'eIcon.search' => 'Redigér søkeskjema',
		'eIcon.login' => 'Redigér innloggingsskjema',
		'eIcon.page' => 'Side:',
	),
	'it' => Array (
	),
	'fr' => Array (
	),
	'es' => Array (
	),
	'nl' => Array (
	),
	'cz' => Array (
	),
	'pl' => Array (
	),
	'si' => Array (
	),
	'fi' => Array (
		'label.toTop' => 'Alkuun',
		'login.username' => 'Käyttjänimi:',
		'login.password' => 'Salasana:',
		'login.login' => 'Sisäänkirjoitus',
		'login.logout' => 'Poistuminen',
		'search.emptySearch' => 'Valitan, hakusi tulos oli tyhjä!',
		'search.resultRange' => 'Hakutulokset alkaen ###RANGELOW###-###RANGEHIGH### kaikkiaan ###TOTAL###  löydetystä.',
		'search.searchResultNext' => 'Seuraava',
		'search.searchResultPrev' => 'Edellinen',
		'search.searchWord' => 'Hakusana:',
		'search.searchIn' => 'Etsi joukosta:',
		'search.headersKeywords' => 'Otsikot ja avainsanat',
		'search.pageContent' => 'Sivun sisältö',
		'search.searchButton' => 'Etsi nyt !',
		'eIcon.html' => 'Muotoile pelkkää HTML sisältöä',
		'eIcon.header' => 'Muotoile otsikkoa',
		'eIcon.subheader' => 'Muotoile alaotsikkoa',
		'eIcon.bodytext' => 'Muotile tekstirunkoa',
		'eIcon.images' => 'Muotoile kuvia',
		'eIcon.caption' => 'Muotoile kuvatekstiä',
		'eIcon.bullets' => 'Muotoile listaa',
		'eIcon.table' => 'Muotoile taulukkoa',
		'eIcon.filelist' => 'Muotoile tiedostolistaa',
		'eIcon.menuSitemap' => 'Muotoile valikkoa / sivustokarttaa',
		'eIcon.recordList' => 'Muotoile tietuelistaa',
		'eIcon.plugin' => 'Muuta/asenna aliohjelmaa',
		'eIcon.multimedia' => 'Muotoile multimedia elementtiä',
		'eIcon.form' => 'Muotoile sähköpostilomaketta',
		'eIcon.search' => 'Muotoile hakuelementtiä',
		'eIcon.login' => 'Muotoile sisäänkirjoituselementtiä',
		'eIcon.page' => 'Sivu:',
	),
	'tr' => Array (
		'label.toTop' => 'Üste',
		'login.username' => 'Kullanýcý adý:',
		'login.password' => 'Þifre:',
		'login.login' => 'Giriþ',
		'login.logout' => 'Çýkýþ',
		'search.emptySearch' => 'Üzgünüm, aramanýz bulunamadý!',
		'search.resultRange' => 'Aramasonuc: ###RANGELOW###-###RANF-GEHIGH### of ###TOTAL###',
		'search.searchResultNext' => 'Sonraki',
		'search.searchResultPrev' => 'Önceki',
		'search.searchWord' => 'Aranacak kelime:',
		'search.searchIn' => 'Arama yap:',
		'search.headersKeywords' => 'Baþlýklar ve Anahtar kelimeler',
		'search.pageContent' => 'Sayfa içeriði',
		'search.searchButton' => 'Þimdi ara!',
		'eIcon.html' => 'Düz HTML içeriðini düzelt',
		'eIcon.header' => 'Baþlýðý düzelt',
		'eIcon.subheader' => 'Altbaþlýðý düzelt',
		'eIcon.bodytext' => 'ana metini düzelt',
		'eIcon.images' => 'Resimleri düzelt',
		'eIcon.caption' => 'Ana resimleri düzelt',
		'eIcon.bullets' => 'Bülten listesini düzelt',
		'eIcon.table' => 'Tabloyu düzelt',
		'eIcon.filelist' => 'Dosya listesini düzelt',
		'eIcon.menuSitemap' => 'menu/site haritasýný düzelt',
		'eIcon.recordList' => 'Kayýt listesini düzelt',
		'eIcon.plugin' => 'eklentileri deðiþtir/Konfigüre et',
		'eIcon.multimedia' => 'Multimedia elementini düzelt',
		'eIcon.form' => 'email formunu düzelt',
		'eIcon.search' => 'arama elementini düzelt',
		'eIcon.login' => 'giriþ elementini düzelt',
		'eIcon.page' => 'Sayfa:',
	),
	'se' => Array (
	),
	'pt' => Array (
	),
	'ru' => Array (
	),
	'ro' => Array (
	),
	'ch' => Array (
	),
	'sk' => Array (
	),
	'lt' => Array (
	),
	'is' => Array (
	),
	'hr' => Array (
	),
	'hu' => Array (
		'label.toTop' => 'Tetejére',
		'login.username' => 'Felhasználónév:',
		'login.password' => 'Jelszó:',
		'login.login' => 'Belépés',
		'login.logout' => 'Kilépés',
		'search.emptySearch' => 'Sajnálom, a keresés üres!',
		'search.resultRange' => 'Keresés eredménye: ###RANGELOW###-###RANGEHIGH### of ###TOTAL###',
		'search.searchResultNext' => 'Következõ',
		'search.searchResultPrev' => 'Elõzõ',
		'search.searchWord' => 'Keresett szó:',
		'search.searchIn' => 'Keresés ebben:',
		'search.headersKeywords' => 'Fejlécek és kulcsszavak',
		'search.pageContent' => 'Oldal tartalom',
		'search.searchButton' => 'Keresés most!',
		'eIcon.html' => 'Sima HTML tartalom szerkesztése',
		'eIcon.header' => 'Fejléc szerkesztése',
		'eIcon.subheader' => 'Alfejléc szerkesztése',
		'eIcon.bodytext' => 'Szövegtörzs szerkesztése',
		'eIcon.images' => 'Képek szerkesztése',
		'eIcon.caption' => 'Kép feliratok szerkesztése',
		'eIcon.bullets' => 'Felsorolás szerkesztése',
		'eIcon.table' => 'Táblázaat szerkesztése',
		'eIcon.filelist' => 'File lista szerkesztése',
		'eIcon.menuSitemap' => 'Menü / oldaltérkép szerkesztése',
		'eIcon.recordList' => 'Rekordlista szerkesztése',
		'eIcon.plugin' => 'Bõvítmény megváltoztatása/beállítása',
		'eIcon.multimedia' => 'Multimédia elem szerkesztése',
		'eIcon.form' => 'Email ûrlap szerkesztése',
		'eIcon.search' => 'Keresési elem szerkesztése',
		'eIcon.login' => 'Belépési elem szerkesztése',
		'eIcon.page' => 'Oldal:',
	),
	'gl' => Array (
	),
	'th' => Array (
	),
	'gr' => Array (
	),
	'hk' => Array (
	),
	'eu' => Array (
	),
	'bg' => Array (
	),
	'br' => Array (
		'label.toTop' => 'Topo',
		'login.username' => 'Usuário:',
		'login.password' => 'Senha:',
		'login.login' => 'Entrar',
		'login.logout' => 'Sair',
		'search.emptySearch' => 'Desculpe, mas sua busca estava vazia!',
		'search.resultRange' => 'Resultado: ###RANGELOW###-###RANGEHIGH### de ###TOTAL###',
		'search.searchResultNext' => 'Próxima',
		'search.searchResultPrev' => 'Anterior',
		'search.searchWord' => 'Busca:',
		'search.searchIn' => 'Buscar em:',
		'search.headersKeywords' => 'Cabeçalhos e palavras-chave',
		'search.pageContent' => 'Conteúdo da página',
		'search.searchButton' => 'Buscar agora!',
		'eIcon.html' => 'Editar conteúdo em HTML',
		'eIcon.header' => 'Editar cabeçalho',
		'eIcon.subheader' => 'Editar sub-cabeçalho',
		'eIcon.bodytext' => 'Editar corpo do texto',
		'eIcon.images' => 'Editar imagens',
		'eIcon.caption' => 'Editar legenda da imagem',
		'eIcon.bullets' => 'Editar lista marcada',
		'eIcon.table' => 'Editar tabela',
		'eIcon.filelist' => 'Editar lista de arquivos',
		'eIcon.menuSitemap' => 'Editar menu / mapa do site',
		'eIcon.recordList' => 'Editar lista de registros',
		'eIcon.plugin' => 'Alterar/configurar plugin',
		'eIcon.multimedia' => 'Editar elemento multimídia',
		'eIcon.form' => 'Editar formulário de e-mail',
		'eIcon.search' => 'Editar elemento de busca',
		'eIcon.login' => 'Editar elemento de entrada',
		'eIcon.page' => 'Página:',
	),
	'et' => Array (
	),
	'ar' => Array (
	),
	'he' => Array (
	),
	'ua' => Array (
	),
	'lv' => Array (
	),
	'jp' => Array (
	),
	'vn' => Array (
	),
	'ca' => Array (
	),
	'ba' => Array (
	),
	'kr' => Array (
	),
);
?>