<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2012-06-22 14:48
$t3libClasses = array(
	't3lib_ajax' => PATH_t3lib . 'class.t3lib_ajax.php',
	't3lib_install' => PATH_t3lib . 'class.t3lib_install.php',
	't3lib_readmail' => PATH_t3lib . 'class.t3lib_readmail.php',
	't3lib_syntaxhl' => PATH_t3lib . 'class.t3lib_syntaxhl.php',
	't3lib_userauthgroup' => PATH_t3lib . 'class.t3lib_userauthgroup.php',
	't3lib_xml' => PATH_t3lib . 'class.t3lib_xml.php'
);
$typo3Classes = array(
	'ext_posmap_pages' => PATH_typo3 . 'move_el.php',
	'ext_posmap_tt_content' => PATH_typo3 . 'move_el.php',
	'ext_tsparser' => PATH_typo3 . 'wizard_tsconfig.php',
	'localfoldertree' => PATH_typo3 . 'class.browse_links.php',
	'rtefoldertree' => PATH_typo3 . 'class.browse_links.php',
	'rtepagetree' => PATH_typo3 . 'class.browse_links.php',
	'tbe_foldertree' => PATH_typo3 . 'class.browse_links.php',
	'tbe_pagetree' => PATH_typo3 . 'class.browse_links.php',
	'transferdata' => PATH_typo3 . 'show_item.php',
);
return array_merge($t3libClasses, $typo3Classes);
?>
