<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2012-06-22 14:48
$typo3Classes = array(
	'ext_posmap_pages' => PATH_typo3 . 'move_el.php',
	'ext_posmap_tt_content' => PATH_typo3 . 'move_el.php',
	'localfoldertree' => PATH_typo3 . 'class.browse_links.php',
	'rtefoldertree' => PATH_typo3 . 'class.browse_links.php',
	'rtepagetree' => PATH_typo3 . 'class.browse_links.php',
	'tbe_foldertree' => PATH_typo3 . 'class.browse_links.php',
	'tbe_pagetree' => PATH_typo3 . 'class.browse_links.php',
	'transferdata' => PATH_typo3 . 'show_item.php',
	'Psr\\Log\\LoggerInterface' => PATH_typo3 . 'contrib/Psr/Log/LoggerInterface.php',
	'Psr\\Log\\InvalidArgumentException' => PATH_typo3 . 'contrib/Psr/Log/InvalidArgumentException.php',
);
return $typo3Classes;
