<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "documentation"
 *
 * Auto generated by Extension Builder 2013-07-04
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Documentation',
	'description' => 'Backend module for TYPO3 to list and show documentation of loaded extensions as well as custom documents.',
	'category' => 'be',
	'author' => 'Xavier Perseguers, Francois Suter',
	'author_email' => 'xavier@typo3.org, francois.suter@typo3.org',
	'author_company' => '',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '6.2.0',
	'constraints' => array(
		'depends' => array(
			'extbase' => '6.2.0-6.2.99',
			'fluid' => '6.2.0-6.2.99',
			'typo3' => '6.2.0-6.2.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);
