<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2010-07-06 16:13

$extensionPath = t3lib_extMgm::extPath('linkvalidator');
return array(
	'tx_linkvalidator_processing' => $extensionPath . 'lib/class.tx_linkvalidator_processing.php',
	'tx_linkvalidator_scheduler_linkadditionalfieldprovider' => $extensionPath . 'lib/class.tx_linkvalidator_scheduler_linkAdditionalFieldProvider.php',
	'tx_linkvalidator_scheduler_link'  => $extensionPath . 'lib/class.tx_linkvalidator_scheduler_link.php',
	'tx_linkvalidator_checkbase'  => $extensionPath . 'lib/class.tx_linkvalidator_checkbase.php',

);
?>