<?php

$LOCAL_LANG = Array (
	'default' => Array (
		'title' => 'Task overview',
		'lReplyAddress' => 'Reply address is your email',
		'lSelf' => 'Self',
		'lSendNew' => 'Send message',
		'lSendReply' => 'Reply to message',
		'listSeparator_Groups' => '__Groups:__',
		'lHomedir' => 'Home dir',
		'lNone' => '[none]',
		'lCreate' => 'Create',
		'lCancel' => 'Cancel',
		'lDelete_warning' => 'Are you sure you want to delete this user?',
		'lDelete' => 'Delete',
		'lUpdate' => 'Update',
	),
	'dk' => Array (
		'title' => 'Overblik over opgaver',
		'lReplyAddress' => 'Retur-adressen er din email',
		'lSelf' => 'Selv',
		'lSendNew' => 'Send besked',
		'lSendReply' => 'Svar pе besked',
		'listSeparator_Groups' => '__Grupper:__',
		'lHomedir' => 'Hjemme-mappe',
		'lNone' => '[ingen]',
		'lCreate' => 'Opret',
		'lCancel' => 'Annullйr',
		'lDelete_warning' => 'Er du sikker pе, at du шnsker at slette denne bruger?',
		'lDelete' => 'Slet',
		'lUpdate' => 'Opdatйr',
	),
	'de' => Array (
		'title' => 'Tasks Ьbersicht',
		'lReplyAddress' => 'Antwortadresse ist Ihre Email Adresse',
		'lSelf' => 'Selbst',
		'lSendNew' => 'Nachricht senden',
		'lSendReply' => 'Nachricht beantworten',
		'listSeparator_Groups' => '__Gruppen:__',
		'lHomedir' => 'Home Verzeichnis',
		'lNone' => '[kein]',
		'lCreate' => 'Anlegen',
		'lCancel' => 'Abbrechen',
		'lDelete_warning' => 'Soll dieser Benutzer wirklich gelцscht werden?',
		'lDelete' => 'Lцschen',
		'lUpdate' => 'Aktualisieren',
	),
	'no' => Array (
		'title' => 'Oversikt over oppgaver',
		'lReplyAddress' => 'Returadressen er din e-post adresse',
		'lSelf' => 'Selv',
		'lSendNew' => 'Send melding',
		'lSendReply' => 'Svar pе melding',
		'listSeparator_Groups' => '__Grupper:__',
		'lHomedir' => 'Hjemme-mappe',
		'lNone' => '[ingen]',
		'lCreate' => 'Opprett',
		'lCancel' => 'Avbryt',
		'lDelete_warning' => 'Er du sikker pе at du шnsker е slette denne brukeren?',
		'lDelete' => 'Slett',
		'lUpdate' => 'Oppdater',
	),
	'it' => Array (
		'title' => 'Visione d\'insieme dei task',
		'lReplyAddress' => 'L\'indirizzo di risposta и la tua e-mail',
		'lSelf' => 'Self',
		'lSendNew' => 'Invia messaggio',
		'lSendReply' => 'Rispondi al  messaggio',
		'listSeparator_Groups' => '__Gruppi:__',
		'lHomedir' => 'Home dir',
		'lNone' => '[none]',
		'lCreate' => 'Crea',
		'lCancel' => 'Cancella',
		'lDelete_warning' => 'Sei sicuro di voler eliminare questo utente?',
		'lDelete' => 'Elimina',
		'lUpdate' => 'Aggiorna',
	),
	'fr' => Array (
		'title' => 'Tвche (rйsumй)',
		'lReplyAddress' => 'L\'adresse de rйponse est votre adresse',
		'lSelf' => 'Personnel',
		'lSendNew' => 'Envoyer le message',
		'lSendReply' => 'Rйpondre au message',
		'listSeparator_Groups' => '_Groups:_',
		'lHomedir' => 'Mes documents',
		'lNone' => '[vide]',
		'lCreate' => 'Crйer',
		'lCancel' => 'Annuler',
		'lDelete_warning' => 'Etes-vous sыre de vouloir supprimer cet utilisateur ?',
		'lDelete' => 'Effacer',
		'lUpdate' => 'Mettre а jour',
	),
	'es' => Array (
		'title' => 'Resъmen de tareas',
		'lReplyAddress' => 'La direcciуn de remitente es la de su email',
		'lSelf' => 'Yo mismo',
		'lSendNew' => 'Enviar mensaje',
		'lSendReply' => 'Contestar mensaje',
		'listSeparator_Groups' => '__Grupos:__',
		'lHomedir' => 'Directorio Home',
		'lNone' => '[ninguno]',
		'lCreate' => 'Crear',
		'lCancel' => 'Cancelar',
		'lDelete_warning' => 'їSeguro que desea borrar este usuario?',
		'lDelete' => 'Borrar',
		'lUpdate' => 'Actualizar',
	),
	'nl' => Array (
		'title' => 'Taakoverzicht',
		'lReplyAddress' => 'De afzender is jouw emailadres',
		'lSelf' => 'Zelf',
		'lSendNew' => 'Verstuur bericht',
		'lSendReply' => 'Bericht beantwoorden',
		'listSeparator_Groups' => '__Groepen:__',
		'lHomedir' => 'Home map',
		'lNone' => '[geen]',
		'lCreate' => 'Aanmaken',
		'lCancel' => 'Annuleren',
		'lDelete_warning' => 'Deze gebruiker verwijderen?',
		'lDelete' => 'Verwijder',
		'lUpdate' => 'Actualiseren',
	),
	'cz' => Array (
		'title' => 'Pшehled ъkolщ',
		'lReplyAddress' => 'Adresa pro odpovмп je vбљ email',
		'lSelf' => 'Vlastnн',
		'lSendNew' => 'Odeslat zprбvu',
		'lSendReply' => 'Odpovмdмt na zprбvu',
		'listSeparator_Groups' => '__Skupiny:__',
		'lHomedir' => 'Domбcн sloћka',
		'lNone' => '[ћбdnй]',
		'lCreate' => 'Vytvoшit',
		'lCancel' => 'Zruљit',
		'lDelete_warning' => 'Jste si jisti, ћe chcete odstranit tohoto uћivatele?',
		'lDelete' => 'Odstranit',
		'lUpdate' => 'Aktualizovat',
	),
	'pl' => Array (
		'title' => 'Przegl±d zadaс',
		'lReplyAddress' => 'Adres zwrotny jest twoim adresem email',
		'lSelf' => 'Wіasne',
		'lSendNew' => 'Wy¶lij wiadomo¶ж',
		'lSendReply' => 'Odpowiedz',
		'listSeparator_Groups' => '__Grupy:__',
		'lHomedir' => 'Katalog domowy',
		'lNone' => '[nic]',
		'lCreate' => 'Utwуrz',
		'lCancel' => 'Anuluj',
		'lDelete_warning' => 'Czy na pewno chcesz usun±ж tego uїytkownika?',
		'lDelete' => 'Usuс',
		'lUpdate' => 'Aktualizuj',
	),
	'si' => Array (
		'title' => 'Pregled nalog',
		'lReplyAddress' => 'Povratni naslov je vaљ email',
		'lSelf' => 'Jaz',
		'lSendNew' => 'Poљlji novo sporoиilo',
		'lSendReply' => 'Poљlji odgovor',
		'listSeparator_Groups' => '__Skupine:__',
		'lHomedir' => 'Domaиa mapa',
		'lNone' => '[niи]',
		'lCreate' => 'Dodaj',
		'lCancel' => 'Prekliиi',
		'lDelete_warning' => 'Ste prepriиani, da ћelite odstraniti tega uporabnika?',
		'lDelete' => 'Briљi',
		'lUpdate' => 'Osveћi',
	),
	'fi' => Array (
		'title' => 'Toimintojen yleispiirteet',
		'lReplyAddress' => 'Vastausosoite on Sinun sдhkцpostiosoitteesi',
		'lSelf' => 'Itse',
		'lSendNew' => 'Lдhet sдhkцpostiviesti',
		'lSendReply' => 'Vastaa sдhkцpostiviestiin',
		'listSeparator_Groups' => '__Ryhmдt:__',
		'lHomedir' => 'Kotihakemisto',
		'lNone' => '[none]',
		'lCreate' => 'Luo',
		'lCancel' => 'Peruuta',
		'lDelete_warning' => 'Oletko varma halutessasi poistaa tдmдn kдyttдjдn?',
		'lDelete' => 'Poista',
		'lUpdate' => 'Pдivitд',
	),
	'tr' => Array (
		'title' => 'Gцrev genel gцrьntьsь',
		'lReplyAddress' => 'Cevap verecek adres emailinizdir',
		'lSelf' => 'Kendi',
		'lSendNew' => 'Mesaj gцndermek',
		'lSendReply' => 'Mesajэ cevaplamak',
		'listSeparator_Groups' => '__Gruplar:__',
		'lHomedir' => 'Giriю dizini',
		'lNone' => '[hiзbiri]',
		'lCreate' => 'Yarat',
		'lCancel' => 'Эptal et',
		'lDelete_warning' => 'Bu kullanэcэyэ silmek istediрinizden eminmisiniz?',
		'lDelete' => 'Sil',
		'lUpdate' => 'Gьncelle',
	),
	'se' => Array (
		'title' => 'Цversikt цver uppgifter',
		'lReplyAddress' => 'Din epostadress anvдnds som svarsadress',
		'lSelf' => 'Sjдlv',
		'lSendNew' => 'Skicka meddelande',
		'lSendReply' => 'Svara pе meddelande',
		'listSeparator_Groups' => '__Grupper:__',
		'lHomedir' => 'Hemkatalog',
		'lNone' => '[inget]',
		'lCreate' => 'Skapa',
		'lCancel' => 'Avbryt',
		'lDelete_warning' => 'Дr du sдker pе att du vill ta bort denna anvдndare?',
		'lDelete' => 'Ta bort',
		'lUpdate' => 'Uppdatera',
	),
	'pt' => Array (
		'title' => 'Histуrico de Tarefas',
		'lReplyAddress' => 'Endereзo de resposta й o seu email',
		'lSelf' => 'Prуprio',
		'lSendNew' => 'Enviar mensagem',
		'lSendReply' => 'Responder а mensagem',
		'listSeparator_Groups' => '__Grupos:__',
		'lHomedir' => 'Directoria raнz',
		'lNone' => '[nenhum]',
		'lCreate' => 'Criar',
		'lCancel' => 'Cancelar',
		'lDelete_warning' => 'Tem a certeza que quer apagar este utilizador?',
		'lDelete' => 'Apagar',
		'lUpdate' => 'Actualizar',
	),
	'ru' => Array (
		'title' => 'Обзор заданий',
		'lReplyAddress' => 'Ваш email как ответный адрес',
		'lSelf' => 'Сам',
		'lSendNew' => 'Послать сообщение',
		'lSendReply' => 'Ответить на сообщение',
		'listSeparator_Groups' => '__Группы:__',
		'lHomedir' => 'Исходная папка',
		'lNone' => '[без]',
		'lCreate' => 'Создать',
		'lCancel' => 'Отменить',
		'lDelete_warning' => 'Вы уверены, хотите стереть этого пользователя?',
		'lDelete' => 'Удалить',
		'lUpdate' => 'Обновить',
	),
	'ro' => Array (
		'title' => 'Vedere a sarcinilor',
		'lReplyAddress' => 'Adresa de raspuns este adresa ta de email',
		'lSelf' => 'Individual',
		'lSendNew' => 'Trimite mesaj',
		'lSendReply' => 'Raspunde la mesaj',
		'listSeparator_Groups' => '__Grupuri:__',
		'lHomedir' => 'Directorul principal',
		'lNone' => '[nimic]',
		'lCreate' => 'Creeaza',
		'lCancel' => 'Anuleaza',
		'lDelete_warning' => 'Esti sigur ca vrei sa stergi acest utilizator?',
		'lDelete' => 'Sterge',
		'lUpdate' => 'Actualizeaza',
	),
	'ch' => Array (
	),
	'sk' => Array (
		'title' => 'Prehѕad ъloh',
		'lReplyAddress' => 'Adresa pre odpoveп je vбљ e-mail',
		'lSelf' => 'Vlastny',
		'lSendNew' => 'Odoslaќ sprбvu',
		'lSendReply' => 'Odpovedaќ na sprбvu',
		'listSeparator_Groups' => '__Skupiny:__',
		'lHomedir' => 'Domбca zloћka',
		'lNone' => '[ћiadne]',
		'lCreate' => 'Vytvoriќ',
		'lCancel' => 'Zruљiќ',
		'lDelete_warning' => 'Ste si naozaj istэ , ћe chcete odstrбniќ akurбt tohoto uћivateѕa?',
		'lDelete' => 'Odstrбniќ',
		'lUpdate' => 'Aktualizovaќ',
	),
	'lt' => Array (
	),
	'is' => Array (
	),
	'hr' => Array (
		'title' => 'Pregled zadataka',
		'lReplyAddress' => 'Adresa za odgovor je vaљ email',
		'lSelf' => 'Sam',
		'lSendNew' => 'Poљalji poruku',
		'lSendReply' => 'Odgovori na poruku',
		'listSeparator_Groups' => '__Grupe:__',
		'lHomedir' => 'Home pretinac',
		'lNone' => '[niљta]',
		'lCreate' => 'Napravi',
		'lCancel' => 'Odustani',
		'lDelete_warning' => 'Sigurno ћelite pobrisati ovog korisnika?',
		'lDelete' => 'Pobriљi',
		'lUpdate' => 'Obnovi',
	),
	'hu' => Array (
	),
	'gl' => Array (
	),
	'th' => Array (
	),
	'gr' => Array (
	),
	'hk' => Array (
	),
	'eu' => Array (
	),
	'bg' => Array (
	),
	'br' => Array (
	),
	'et' => Array (
		'title' => 'Ьlesande ьlevaade',
		'lReplyAddress' => 'Emili aadress, kuhu saata vastus',
		'lSelf' => 'Ise',
		'lSendNew' => 'Saada kiri',
		'lSendReply' => 'Vasta kirjale',
		'listSeparator_Groups' => '__Grupid:__',
		'lHomedir' => 'Kodukataloog',
		'lNone' => '[tьhi]',
		'lCreate' => 'Loo',
		'lCancel' => 'Katkesta',
		'lDelete_warning' => 'Olete kindel, et soovite selle kasutaja kustutada?',
		'lDelete' => 'Kustuta',
		'lUpdate' => 'Uuenda',
	),
	'ar' => Array (
	),
	'he' => Array (
	),
	'ua' => Array (
	),
);
?>