<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2011-04-07 22:16

$extensionPath = t3lib_extMgm::extPath('dbal');
return array(
	'tx_dbal_querycache' => $extensionPath . 'lib/class.tx_dbal_querycache.php',
);
?>