<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2010-04-06 21:47


$extensionPath = t3lib_extMgm::extPath('dbal');
return array(
	'tx_dbal_querycache' => $extensionPath . 'lib/class.tx_dbal_querycache.php',
	'tx_dbal_sqlengine' => $extensionPath . 'lib/class.tx_dbal_sqlengine.php',
	'ux_t3lib_sqlparser' => $extensionPath . 'class.ux_t3lib_sqlparser.php',
);
?>