<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2010-11-13 17:45
$extensionPath = \TYPO3\CMS\Core\Utility\ExtensionManagementUtility::extPath('version');
return array(
	'tx_version_tcemain_commandmap' => $extensionPath . 'class.tx_version_tcemain_commandmap.php',
	'tx_version_cm1' => $extensionPath . 'cm1/index.php',
	'tx_version_gui' => $extensionPath . 'class.tx_version_gui.php',
	'tx_version_tcemain' => $extensionPath . 'class.tx_version_tcemain.php',
	'tx_version_tasks_autopublish' => $extensionPath . 'tasks/class.tx_version_tasks_autopublish.php',
	'tx_version_preview' => $extensionPath . 'Classes/Preview.php'
);
?>