<?php
return array(
    'TYPO3\\CMS\\Frontend\\ContentObject\\FlowplayerContentObject' => \FoT3\Mediace\ContentObject\FlowplayerContentObject::class,
    'TYPO3\\CMS\\Frontend\\ContentObject\\MediaContentObject' => \FoT3\Mediace\ContentObject\MediaContentObject::class,
    'TYPO3\\CMS\\Frontend\\ContentObject\\MultimediaContentObject' => \FoT3\Mediace\ContentObject\MultimediaContentObject::class,
    'TYPO3\\CMS\\Frontend\\ContentObject\\QuicktimeObjectContentObject' => \FoT3\Mediace\ContentObject\QuicktimeObjectContentObject::class,
    'TYPO3\\CMS\\Frontend\\ContentObject\\ShockwaveFlashObjectContentObject' => \FoT3\Mediace\ContentObject\ShockwaveFlashObjectContentObject::class,
    'TYPO3\\CMS\\Frontend\\MediaWizard\MediaWizardProvider' => \FoT3\Mediace\MediaWizard\MediaWizardProvider::class,
    'TYPO3\\CMS\\Frontend\\MediaWizard\MediaWizardProviderInterface' => \FoT3\Mediace\MediaWizard\MediaWizardProviderInterface::class,
    'TYPO3\\CMS\\Frontend\\MediaWizard\MediaWizardProviderManager' => \FoT3\Mediace\MediaWizard\MediaWizardProviderManager::class,
    'TYPO3\\CMS\\Mediace\\ContentObject\\FlowplayerContentObject' => \FoT3\Mediace\ContentObject\FlowplayerContentObject::class,
    'TYPO3\\CMS\\Mediace\\ContentObject\\MediaContentObject' => \FoT3\Mediace\ContentObject\MediaContentObject::class,
    'TYPO3\\CMS\\Mediace\\ContentObject\\MultimediaContentObject' => \FoT3\Mediace\ContentObject\MultimediaContentObject::class,
    'TYPO3\\CMS\\Mediace\\ContentObject\\QuicktimeObjectContentObject' => \FoT3\Mediace\ContentObject\QuicktimeObjectContentObject::class,
    'TYPO3\\CMS\\Mediace\\ContentObject\\ShockwaveFlashObjectContentObject' => \FoT3\Mediace\ContentObject\ShockwaveFlashObjectContentObject::class,
    'TYPO3\\CMS\\Mediace\\Hooks\\PageLayoutView\\MultimediaPreviewRenderer' => \FoT3\Mediace\Hooks\PageLayoutView\MultimediaPreviewRenderer::class,
    'TYPO3\\CMS\\Mediace\\MediaWizard\MediaWizardProvider' => \FoT3\Mediace\MediaWizard\MediaWizardProvider::class,
    'TYPO3\\CMS\\Mediace\\MediaWizard\MediaWizardProviderInterface' => \FoT3\Mediace\MediaWizard\MediaWizardProviderInterface::class,
    'TYPO3\\CMS\\Mediace\\MediaWizard\MediaWizardProviderManager' => \FoT3\Mediace\MediaWizard\MediaWizardProviderManager::class,
    'tslib_content_FlowPlayer' => \FoT3\Mediace\ContentObject\FlowPlayerContentObject::class,
    'tslib_content_Media' => \FoT3\Mediace\ContentObject\MediaContentObject::class,
    'tslib_content_Multimedia' => \FoT3\Mediace\ContentObject\MultimediaContentObject::class,
    'tslib_content_QuicktimeObject' => \FoT3\Mediace\ContentObject\QuicktimeObjectContentObject::class,
    'tslib_content_ShockwaveFlashObject' => \FoT3\Mediace\ContentObject\ShockwaveFlashObjectContentObject::class,
    'tslib_mediaWizardCoreProvider' => \FoT3\Mediace\MediaWizard\MediaWizardProvider::class,
    'tslib_mediaWizardProvider' => \FoT3\Mediace\MediaWizard\MediaWizardProviderInterface::class,
    'tslib_mediaWizardManager' => \FoT3\Mediace\MediaWizard\MediaWizardProviderManager::class,
);
