<?php

$LOCAL_LANG = Array (
	'default' => Array (
		'action_noType' => 'Error: The action had no type defined.',
		'action_notReady' => 'Error: The action configuration is not finished.',
		'action_download_file' => 'Click here to download the exported data in a file',
		'action_error' => 'Action error!',
		'action_BEu_hidden' => 'Disable user',
		'action_BEu_username' => 'Login name',
		'action_BEu_password' => 'Password',
		'action_BEu_realName' => 'Real name',
		'action_BEu_email' => 'Email',
		'action_BEu_usergroups' => 'Member of groups',
		'action_t2_result' => 'Result of query',
		'action_Create' => 'Create Backend User',
		'action_Update' => 'Update Backend User',
		'action_t1_listOfUsers' => 'List of backend users',
		'action_BEu_db_mount' => 'Pagetree starting points',
		'action_t4_edit' => 'Select record to edit:',
	),
	'dk' => Array (
		'action_noType' => 'Fejl: Handlingen havde ikke en defineret type.',
		'action_notReady' => 'Fejl: Handlingen er ikke fжrdig-konfigureret.',
		'action_download_file' => 'Klik her for at downloade de eksporterede data til en fil',
		'action_error' => 'Fejl i handlingen!',
		'action_BEu_hidden' => 'Skjul brugeren',
		'action_BEu_username' => 'Login navn',
		'action_BEu_password' => 'Password',
		'action_BEu_realName' => 'Person navn',
		'action_BEu_email' => 'Email',
		'action_BEu_usergroups' => 'Medlem af grupperne',
		'action_t2_result' => 'Resultat af forespшrgsel',
		'action_Create' => 'Opret opdateringsbruger',
		'action_Update' => 'Opdatйr bruger',
		'action_t1_listOfUsers' => 'Liste af opdateringsbrugere',
		'action_BEu_db_mount' => 'Startpunkter til sidetrжet',
		'action_t4_edit' => 'Vжlg et element at redigere:',
	),
	'de' => Array (
		'action_noType' => 'Fehler: Fьr die Action wurde kein Typ definiert.',
		'action_notReady' => 'Fehler: Die Konfiguration der Action ist nicht abgeschlossen.',
		'action_download_file' => 'Klicken Sie hier, um die exportierten Daten als Datei herunterzuladen.',
		'action_error' => 'Befehlsfehler!',
		'action_BEu_hidden' => 'Benutzer deaktivieren',
		'action_BEu_username' => 'Login Name',
		'action_BEu_password' => 'Passwort',
		'action_BEu_realName' => 'Richtiger Name',
		'action_BEu_email' => 'Email',
		'action_BEu_usergroups' => 'Mitglieder der Gruppen',
		'action_t2_result' => 'Ergebnis der Anfrage',
		'action_Create' => 'Backend User anlegen',
		'action_Update' => 'Backend User aktualisieren',
		'action_t1_listOfUsers' => 'Liste der Backend User',
		'action_BEu_db_mount' => 'Seitenbaum Startpunkte',
		'action_t4_edit' => 'Zu bearbeitenden Datensatz auswдhlen:',
	),
	'no' => Array (
		'action_noType' => 'Feil: Handlingen hadde ikke en definert type.',
		'action_notReady' => 'Feil: Handlingen er ikke ferdigkonfigurert.',
		'action_download_file' => 'Klikk her for е laste ned de eksporterte dataene til en fil',
		'action_error' => 'Feil handling',
		'action_BEu_hidden' => 'Skjul brukeren',
		'action_BEu_username' => 'Brukernavn',
		'action_BEu_password' => 'Passord',
		'action_BEu_realName' => 'Navn',
		'action_BEu_email' => 'E-post',
		'action_BEu_usergroups' => 'Medlem av gruppene',
		'action_t2_result' => 'Resultat av forespшrsel',
		'action_Create' => 'Opprett oppdateringsbruker (Backend)',
		'action_Update' => 'Oppdater oppdateringsbruker',
		'action_t1_listOfUsers' => 'Liste over oppdateringsbrukere',
		'action_BEu_db_mount' => 'Startpunkter i sidetreet',
		'action_t4_edit' => 'Velg et element е redigere:',
	),
	'it' => Array (
		'action_noType' => 'Errore: L\'azione non ha un tipo definito.',
		'action_notReady' => 'Errore: L\'azione di configurazione non e\' terminata.',
		'action_download_file' => 'Clicca qui per scaricare i dati in un file',
		'action_error' => 'Errore!',
		'action_BEu_hidden' => 'Disabilita utente',
		'action_BEu_username' => 'Login',
		'action_BEu_password' => 'Password',
		'action_BEu_realName' => 'Nome',
		'action_BEu_email' => 'Email',
		'action_BEu_usergroups' => 'Membro dei gruppi',
		'action_t2_result' => 'Risultato della query',
		'action_Create' => 'Crea un utente backend',
		'action_Update' => 'Aggiorna un utente backend',
		'action_t1_listOfUsers' => 'Elenco utenti backend',
		'action_BEu_db_mount' => 'Punto di partenza dell\'albero delle pagine',
		'action_t4_edit' => 'Seleziona record da modificare:',
	),
	'fr' => Array (
		'action_noType' => 'Erreur: L\'action n\'a pas de type dйfini.',
		'action_notReady' => 'Erreur: La configuration de l\'action n\'est pas finie.',
		'action_download_file' => 'Ciquer ici pour tйlйcharger les donnйes exportйes.',
		'action_error' => 'Erreur d\'action!',
		'action_BEu_hidden' => 'Dйsactiver l\'utilisateur',
		'action_BEu_username' => 'Nom d\'identification',
		'action_BEu_password' => 'Mot de passe',
		'action_BEu_realName' => 'Nom',
		'action_BEu_email' => 'E-mail',
		'action_BEu_usergroups' => 'Membre de(s) groupe(s)',
		'action_t2_result' => 'Rйsultat de la requиte',
		'action_Create' => 'Crйer un utilisateur Backend',
		'action_Update' => 'Modifier une utilisateur Backend',
		'action_t1_listOfUsers' => 'Lister les utilisateurs Backend',
		'action_BEu_db_mount' => 'Dйparts de l\'arborescence',
		'action_t4_edit' => 'Sйlйctionnez un enregistrement а йditer:',
	),
	'es' => Array (
		'action_noType' => 'Error: La acciуn no tiene un tipo definido.',
		'action_notReady' => 'Error: La configuraciуn de la acciуn no estб completada.',
		'action_download_file' => 'Presione aquн para descargar los datos exportados en un archivo',
		'action_error' => 'ЎError de la acciуn!',
		'action_BEu_hidden' => 'Deshabilitar usuario',
		'action_BEu_username' => 'Login',
		'action_BEu_password' => 'Password',
		'action_BEu_realName' => 'Nombre completo',
		'action_BEu_email' => 'Email',
		'action_BEu_usergroups' => 'Miembro de los grupos',
		'action_t2_result' => 'Resultado de la bъsqueda',
		'action_Create' => 'Crear usuario del Backend',
		'action_Update' => 'Actualizar usuario del Backend',
		'action_t1_listOfUsers' => 'Lista de usuarios del Backend',
		'action_BEu_db_mount' => 'Puntos de inicio en el бrbol de pбginas',
	),
	'nl' => Array (
		'action_noType' => 'Fout: Bij deze aktie was geen type gedefinieerd.',
		'action_notReady' => 'Fout: De configuratie van deze aktie is nog niet voltooid.',
		'action_download_file' => 'Klik hier om de geexporteerde gegevens te downloaden als een bestand',
		'action_error' => 'Actie fout!',
		'action_BEu_hidden' => 'Deactiveer gebruiker',
		'action_BEu_username' => 'Login naam',
		'action_BEu_password' => 'Wachtwoord',
		'action_BEu_realName' => 'Naam',
		'action_BEu_email' => 'Email',
		'action_BEu_usergroups' => 'Lid van de volgende groepen',
		'action_t2_result' => 'Resultaat van zoekopdracht',
		'action_Create' => 'BeheerSite gebruiker aanmaken',
		'action_Update' => 'BeheerSite gebruiker actualiseren',
		'action_t1_listOfUsers' => 'Lijst van BeheerSite gebruikers',
		'action_BEu_db_mount' => 'Paginastructuur startpunten',
		'action_t4_edit' => 'Selecteer te bewerken record',
	),
	'cz' => Array (
		'action_noType' => 'Chyba: Akce nemб definovanэ typ.',
		'action_notReady' => 'Chyba: Konfigurace akce nebyla dokonиena.',
		'action_download_file' => 'Kliknмte zde, abyste stбhli exportovanб data do souboru.',
		'action_error' => 'Chyba akce!',
		'action_BEu_hidden' => 'Pozastavit uћivatele',
		'action_BEu_username' => 'Login jmйno',
		'action_BEu_password' => 'Heslo',
		'action_BEu_realName' => 'Opravdovй jmйno',
		'action_BEu_email' => 'Email',
		'action_BEu_usergroups' => 'Иlen skupin',
		'action_t2_result' => 'Vэsledek dotazu',
		'action_Create' => 'Vytvoшit uћivatelel backendu',
		'action_Update' => 'Aktualizovat uћivatele backendu',
		'action_t1_listOfUsers' => 'Seznam uћivatelщ backendu',
		'action_BEu_db_mount' => 'Zaибtky stromu strбnek',
		'action_t4_edit' => 'Zvolte zбznam k editaci:',
	),
	'pl' => Array (
		'action_noType' => 'Bі±d: Akcja nie ma zdefiniowanego typu.',
		'action_notReady' => 'Bіad: Konfiguracja Akcji nie zostaіa zakoсczona.',
		'action_download_file' => 'Kliknij tutaj aby pobraж dane w postaci pliku',
		'action_error' => 'Bі±d akcji!',
		'action_BEu_hidden' => 'Wyі±cz uїytkownika',
		'action_BEu_username' => 'Uїytkownik',
		'action_BEu_password' => 'Hasіo',
		'action_BEu_realName' => 'Nazwa uїytkownika',
		'action_BEu_email' => 'Email',
		'action_BEu_usergroups' => 'Czіonek grup',
		'action_t2_result' => 'Wynik wyszukiwania',
		'action_Create' => 'Utwуrz uїytkownika',
		'action_Update' => 'Aktualizuj uїytkownika',
		'action_t1_listOfUsers' => 'Lista uїytkownikуw',
		'action_BEu_db_mount' => 'Strona startowa',
		'action_t4_edit' => 'Wybierz rekord do edycji:',
	),
	'si' => Array (
		'action_noType' => 'Napaka: ta akcija ni imela nastavljenega tipa.',
		'action_notReady' => 'Napaka: konfiguriranje akcije љe ni konиano.',
		'action_download_file' => 'Kliknite tukaj za prenos izvoћenih podatkov v datoteki',
		'action_error' => 'Napaka akcije!',
		'action_BEu_hidden' => 'Onemogoиi uporabnika',
		'action_BEu_username' => 'Prijavno ime',
		'action_BEu_password' => 'Geslo',
		'action_BEu_realName' => 'Pravo ime',
		'action_BEu_email' => 'Email',
		'action_BEu_usergroups' => 'Иlan skupin',
		'action_t2_result' => 'Razultati poizvedbe',
		'action_Create' => 'Ustvari uporabnika',
		'action_Update' => 'Osveћi uporabnika',
		'action_t1_listOfUsers' => 'Seznam uporabnikov',
		'action_BEu_db_mount' => 'Zaиetna mesta v drevesu strani',
	),
	'fi' => Array (
		'action_noType' => 'Virhe: Toiminnolle ei ole mддritelty tyyppiд.',
		'action_notReady' => 'Virhe: Toiminnon mддrittelyд ei ole saatettu loppuun.',
		'action_download_file' => 'Nдpsдytд tдhдn hakeaksesi ulkoistetun datan tiedostoon',
		'action_error' => 'Toiminta virhe!',
		'action_BEu_hidden' => 'Lopeta kдyttдjд',
		'action_BEu_username' => 'Sisддnkirjoitus nimi',
		'action_BEu_password' => 'Salasana',
		'action_BEu_realName' => 'Todellinen nimi',
		'action_BEu_email' => 'Sдhkцposti',
		'action_BEu_usergroups' => 'Jдsen ryhmissд',
		'action_t2_result' => 'Kyselyn tulos',
		'action_Create' => 'Luo backend-kдyttдjд',
		'action_Update' => 'Pдivitд backend-kдyttдjд',
		'action_t1_listOfUsers' => 'Luettelo backend-kдyttдjistд',
		'action_BEu_db_mount' => 'Sivurakenteen aloituskohdat',
		'action_t4_edit' => 'Valitse muokattava tietue:',
	),
	'tr' => Array (
		'action_noType' => 'Hata: Aksiyon tipi belirlenemedi.',
		'action_notReady' => 'Hata: Aksiyon konfigьrasyonu bitirilemedi.',
		'action_download_file' => 'Bir dosya iзinde ihraз veriyi indirmek iзin tэklayэnэz',
		'action_error' => 'Aksiyon hatasэ!',
		'action_BEu_hidden' => 'Devre dэюэ bэrakэlan kullanэcэ',
		'action_BEu_username' => 'Giriю ismi',
		'action_BEu_password' => 'Юifre',
		'action_BEu_realName' => 'Gerзek adэ',
		'action_BEu_email' => 'E-mail',
		'action_BEu_usergroups' => 'Grup ьyesi',
		'action_t2_result' => 'Sorunun yanэtэ',
		'action_Create' => 'Arkaplan kullanэcэ yaratma',
		'action_Update' => 'Arkaplan kullanэcэ gьncelleme',
		'action_t1_listOfUsers' => 'Arkaplan kullanэcэlarэn listelenmesi',
		'action_BEu_db_mount' => 'Sayfa aрacэ baюlama noktalarэ',
		'action_t4_edit' => 'Kayэt dьzenlemeyi seз:',
	),
	'se' => Array (
		'action_noType' => 'Ett fel har uppstеtt: Denna aktivitet var obestдmd.',
		'action_notReady' => 'Ett fel har uppstеtt: Den instдllda aktiviteten har inte slutfцrts.',
		'action_download_file' => 'Klicka hдr fцr att ladda ner den exporterade datan i en fil',
		'action_error' => 'Fel i aktivitet!',
		'action_BEu_hidden' => 'Utestдng anvдndare',
		'action_BEu_username' => 'Inloggningsnamn',
		'action_BEu_password' => 'Lцsenord',
		'action_BEu_realName' => 'Riktigt namn',
		'action_BEu_email' => 'Epost',
		'action_BEu_usergroups' => 'Medlem i grupper',
		'action_t2_result' => 'Svar pе fцrfrеgan',
		'action_Create' => 'Skapa Backend-anvдndare',
		'action_Update' => 'Uppdatera Backend-anvдndare',
		'action_t1_listOfUsers' => 'Lista pе Backend-anvдndare',
		'action_BEu_db_mount' => 'Startpunkt fцr sidtrдd',
		'action_t4_edit' => 'Vдlj vilket data som skall дndras:',
	),
	'pt' => Array (
		'action_noType' => 'Erro: A acзгo nгo tem tipo definido.',
		'action_notReady' => 'Erro: A configuraзгo da acзгo nгo estб concluнda.',
		'action_download_file' => 'Clique aqui para obter os dados exportados num ficheiro',
		'action_error' => 'Erro de Acзгo!',
		'action_BEu_hidden' => 'Desactivar utilizador',
		'action_BEu_username' => 'Nome de Utilizador',
		'action_BEu_password' => 'Senha',
		'action_BEu_realName' => 'Nome real',
		'action_BEu_email' => 'Email',
		'action_BEu_usergroups' => 'Membro dos grupos',
		'action_t2_result' => 'Resultado da pesquisa',
		'action_Create' => 'Criar Utilizador do Gestor',
		'action_Update' => 'Actualizar Utilizador do Gestor',
		'action_t1_listOfUsers' => 'Listar Utilizadores do Gestor',
		'action_BEu_db_mount' => 'Pontos de нnicio da Бrvore de pбginas',
		'action_t4_edit' => 'Selecione registo a editar:',
	),
	'ru' => Array (
		'action_noType' => 'Ошибка: не был определен тип команды.',
		'action_notReady' => 'Ошибка: конфигурация команды не окончена.',
		'action_download_file' => 'Нажмите здесь, чтобы сгрузить экспортированные данные в виде файла',
		'action_error' => 'Ошибка в команде!',
		'action_BEu_hidden' => 'Выключить пользователя',
		'action_BEu_username' => 'Ник пользователя (login-имя)',
		'action_BEu_password' => 'Пароль',
		'action_BEu_realName' => 'Полное Имя',
		'action_BEu_email' => 'Email',
		'action_BEu_usergroups' => 'Член групп',
		'action_t2_result' => 'Результат запроса',
		'action_Create' => 'Создать внутреннего пользователя',
		'action_Update' => 'Обновить данные внутреннего пользователя',
		'action_t1_listOfUsers' => 'Список внутренних пользователей',
		'action_BEu_db_mount' => 'Исходные точки дерева страниц',
		'action_t4_edit' => 'Выберите запись для правки:',
	),
	'ro' => Array (
	),
	'ch' => Array (
	),
	'sk' => Array (
		'action_noType' => 'Chyba: Akcia nema definovanэ typ.',
		'action_notReady' => 'Chyba: Konfigurбcie akcie nebola ukonиenб.',
		'action_download_file' => 'Tu Klikni, aby si stiahol exportovanй ъdaje do sъboru.',
		'action_error' => 'Chyba akcie!',
		'action_BEu_hidden' => 'Zablokuj uћнvateѕa',
		'action_BEu_username' => 'Prihlasovacie meno',
		'action_BEu_password' => 'Heslo',
		'action_BEu_realName' => 'Skutoиnй meno',
		'action_BEu_email' => 'Email',
		'action_BEu_usergroups' => 'Иlen skupнn',
		'action_t2_result' => 'Vэsledok otбzky',
		'action_Create' => 'Vytvoшit uћivatelel backendu',
		'action_Update' => 'Aktualizovat uћнvateѕa backendu',
		'action_t1_listOfUsers' => 'Zoznam uћнvateѕov backendu',
		'action_BEu_db_mount' => 'Poиiatky stromu strбnok',
		'action_t4_edit' => 'Zvoѕte zбznam k editбcii:',
	),
	'lt' => Array (
	),
	'is' => Array (
	),
	'hr' => Array (
		'action_noType' => 'Greљka: Postupak nema definirani tip.',
		'action_notReady' => 'Greљka: Konfiguriranje postupka nije zavrљeno.',
		'action_download_file' => 'Klikni ovdje za snimanje eksportiranih podataka u datoteku',
		'action_error' => 'Greљka u postupku!',
		'action_BEu_hidden' => 'Onemoguжi korisnika',
		'action_BEu_username' => 'Korisniиko ime',
		'action_BEu_password' => 'Zaporka',
		'action_BEu_realName' => 'Stvarno ime korisnika',
		'action_BEu_email' => 'Email',
		'action_BEu_usergroups' => 'Иlan grupa',
		'action_t2_result' => 'Ishod upita',
		'action_Create' => 'Kreiraj korisnika backend-a',
		'action_Update' => 'Obnovi korisnika backend-a',
		'action_t1_listOfUsers' => 'Popis korisnika backend-a',
		'action_BEu_db_mount' => 'Poиetne toиke stabla stranica',
		'action_t4_edit' => 'Odaberi zapis za pregled:',
	),
	'hu' => Array (
	),
	'gl' => Array (
	),
	'th' => Array (
	),
	'gr' => Array (
	),
	'hk' => Array (
	),
	'eu' => Array (
	),
	'bg' => Array (
	),
	'br' => Array (
	),
	'et' => Array (
	),
	'ar' => Array (
	),
	'he' => Array (
	),
	'ua' => Array (
	),
);
?>