<?php
/**
 * Language labels for plugin Acronym of htmlArea RTE (extension: rtehtmlarea)
 * 
 * This file is detected by the translation tool.
 */

$LOCAL_LANG = Array (
	'default' => Array (
		'Type_of_abridged_form' => 'Acronym or Abbreviation?',
		'Term_to_abridge' => 'Term to abridge',
		'Defined_term' => 'Pre-defined Acronyms and Abbreviations',
		'Term' => 'Term:',
		'Unabridged_term' => 'Unabridged Term:',
		'Select_a_term' => 'Select a term',
		'Abridged_term' => 'Abridged Term:',
		'Acronym' => 'Acronym',
		'Abbreviation' => 'Abbreviation',
		'Select_an_acronym' => 'Select an acronym or abbreviation',
		'Use_this_term' => 'Use this term:',
		'Use_this_term_explain' => 'Associate this term to the current selection',
		'OK' => 'OK',
		'Delete' => 'Delete',
		'Cancel' => 'Cancel',
	),
	'dk' => Array (
		'Type_of_abridged_form' => 'Akronym eller forkortelse?',
		'Term_to_abridge' => 'Udtryk der skal forkortes',
		'Defined_term' => 'Predefinerede akronymer og forkortelser',
		'Term' => 'Udtryk:',
		'Unabridged_term' => 'Fuldstжndigt udtryk:',
		'Select_a_term' => 'Vжlg et udtryk',
		'Abridged_term' => 'Forkortet udtryk:',
		'Acronym' => 'Akronym',
		'Abbreviation' => 'Forkortelse',
		'Select_an_acronym' => 'Vжlg et akronym eller en forkortelse',
		'Use_this_term' => 'Brug dette udtryk:',
		'Use_this_term_explain' => 'Tilknyt dette udtryk til nuvжrende markering',
		'OK' => 'OK',
		'Delete' => 'Slet',
		'Cancel' => 'Annuller',
	),
	'de' => Array (
		'Type_of_abridged_form' => 'Akronym oder Abkьrzung?',
		'Term_to_abridge' => 'Abzukьrzender Begriff',
		'Defined_term' => 'Vordefinierte Akronyme oder Abkьrzungen',
		'Term' => 'Begriff:',
		'Unabridged_term' => 'Voll ausgeschriebener Begriff:',
		'Select_a_term' => 'Wдhlen Sie einen Begriff',
		'Abridged_term' => 'Abgekьrzter Begriff:',
		'Acronym' => 'Akronym',
		'Abbreviation' => 'Abkьrzung',
		'Select_an_acronym' => 'Wдhlen Sie ein Akronym oder eine Abkьrzung',
		'Use_this_term' => 'Diesen Begriff verwenden:',
		'Use_this_term_explain' => 'Diesen Begriff der derzeitigen Auswahl zuweisen',
		'OK' => 'OK',
		'Delete' => 'Lцschen',
		'Cancel' => 'Abbrechen',
	),
	'no' => Array (
		'Type_of_abridged_form' => 'Akronym eller forkortelse?',
		'Term_to_abridge' => 'Uttrykk е forkorte',
		'Defined_term' => 'Forhеndsdefinerte akronymer og forkortelser',
		'Term' => 'Uttrykk:',
		'Unabridged_term' => 'Fullstendig uttrykk:',
		'Select_a_term' => 'Velg et uttrykk',
		'Abridged_term' => 'Forkortet uttrykk:',
		'Acronym' => 'Akronym',
		'Abbreviation' => 'Forkortelse',
		'Select_an_acronym' => 'Velg et akronym eller en forkortelse',
		'Use_this_term' => 'Bruk dette uttrykket:',
		'Use_this_term_explain' => 'Assosier dette uttrykket til den nеvжrende markeringen',
		'OK' => 'OK',
		'Delete' => 'Slett',
		'Cancel' => 'Avbryt',
	),
	'it' => Array (
		'Type_of_abridged_form' => 'Acronimo o Abbreviazione?',
		'Term_to_abridge' => 'Termine da accorciare',
		'Defined_term' => 'Acronimi e Abbreviazioni predefinite',
		'Term' => 'Termine:',
		'Unabridged_term' => 'Termine non abbreviato:',
		'Select_a_term' => 'Seleziona un termine',
		'Abridged_term' => 'Termine abbreviato:',
		'Acronym' => 'Acronimo',
		'Abbreviation' => 'Abbreviazione',
		'Select_an_acronym' => 'Seleziona un acronimo o un\'abbreviazione',
		'Use_this_term' => 'Usa questo termine',
		'Use_this_term_explain' => 'Associa questo termine alla selezione corrente',
		'OK' => 'OK',
		'Delete' => 'Elimina',
		'Cancel' => 'Annulla',
	),
	'fr' => Array (
		'Type_of_abridged_form' => 'Acronyme ou abrйviation?',
		'Term_to_abridge' => 'Terme а abrйger',
		'Defined_term' => 'Acronymes et abrйviations prй-dйfinis',
		'Term' => 'Terme:',
		'Unabridged_term' => 'Terme non abrйgй:',
		'Select_a_term' => 'Sйlectionnez un terme',
		'Abridged_term' => 'Terme abrйgй:',
		'Acronym' => 'Acronyme',
		'Abbreviation' => 'Abrйviation',
		'Select_an_acronym' => 'Sйlectionnez un acronyme ou une abrйviation',
		'Use_this_term' => 'Utiliser ce terme:',
		'Use_this_term_explain' => 'Associer ce terme а la sйlection courante',
		'OK' => 'OK',
		'Delete' => 'Effacer',
		'Cancel' => 'Annuler',
	),
	'es' => Array (
	),
	'nl' => Array (
		'Type_of_abridged_form' => 'Acroniem of afkorting?',
		'Term_to_abridge' => 'Term om af te korten',
		'Defined_term' => 'Voorgedefiniлerde acroniemen en afkortingen',
		'Term' => 'Term:',
		'Unabridged_term' => 'Niet afgekorte term:',
		'Select_a_term' => 'Selecteer een term:',
		'Abridged_term' => 'Afgekorte term:',
		'Acronym' => 'Acroniem',
		'Abbreviation' => 'Afkorting',
		'Select_an_acronym' => 'Selecteer een acroniem of een afkorting',
		'Use_this_term' => 'Gebruik deze term:',
		'Use_this_term_explain' => 'Associeer deze term met de huidige selectie',
		'OK' => 'OK',
		'Delete' => 'Verwijderen',
		'Cancel' => 'Annuleren',
	),
	'cz' => Array (
		'Type_of_abridged_form' => 'Akronym nebo zkratka?',
		'Term_to_abridge' => 'Termнn pro zkrбcenн',
		'Defined_term' => 'Pшeddefinovanй akronymy a zkratky',
		'Term' => 'Vэraz:',
		'Unabridged_term' => 'Nezkrбcenэ vэraz:',
		'Select_a_term' => 'Vyberte vэraz',
		'Abridged_term' => 'Zkrбcenэ vэraz:',
		'Acronym' => 'Akronym',
		'Abbreviation' => 'Zkratka',
		'Select_an_acronym' => 'Vyberte akronym nebo zkratku',
		'Use_this_term' => 'Pouћнt tento vэraz:',
		'Use_this_term_explain' => 'Pшipojit tento vэraz k aktuбlnнmu vэbмru',
		'OK' => 'OK',
		'Delete' => 'Smazat',
		'Cancel' => 'Storno',
	),
	'pl' => Array (
	),
	'si' => Array (
	),
	'fi' => Array (
		'Type_of_abridged_form' => 'Akronyymi vai lyhenne ?',
		'Term_to_abridge' => 'Suppea termi',
		'Defined_term' => 'Edeltд mддritetyt akronyymit ja lyhenteet',
		'Term' => 'Termi:',
		'Unabridged_term' => 'Suppea termi:',
		'Select_a_term' => 'Valitse termi',
		'Abridged_term' => 'Suppea termi:',
		'Acronym' => 'Akronyymi',
		'Abbreviation' => 'Lyhenne',
		'Select_an_acronym' => 'Valitse akronyymi tai lyhenne',
		'Use_this_term' => 'Kдytд tдtдд termiд:',
		'Use_this_term_explain' => 'Liitд tдmд termi nykyiseen valintaan',
		'OK' => 'OK',
		'Delete' => 'Poista',
		'Cancel' => 'Peruuta',
	),
	'tr' => Array (
	),
	'se' => Array (
	),
	'pt' => Array (
	),
	'ru' => Array (
		'Type_of_abridged_form' => 'Акроним или аббревиатура?',
		'Term_to_abridge' => 'Термин для сокращения',
		'Defined_term' => 'Предопределённые акронимы и аббревиатуры',
		'Term' => 'Термин:',
		'Unabridged_term' => 'Несокращенный термин',
		'Select_a_term' => 'Выберите термин',
		'Abridged_term' => 'Сокращенный термин',
		'Acronym' => 'Акроним',
		'Abbreviation' => 'Аббревиатура',
		'Select_an_acronym' => 'Выбирите акроним или аббревиатуру',
		'Use_this_term' => 'Используйте этот термин',
		'Use_this_term_explain' => 'Ассоциировать термин с выделением',
		'OK' => 'OK',
		'Delete' => 'Удалить',
		'Cancel' => 'Отмена',
	),
	'ro' => Array (
	),
	'ch' => Array (
	),
	'sk' => Array (
		'Type_of_abridged_form' => 'Akronym alebo skratka?',
		'Term_to_abridge' => 'Termнn pre skrбtenie',
		'Defined_term' => 'Preddefinovй akronymy a skratky',
		'Term' => 'Termнn:',
		'Unabridged_term' => 'Neskrбtenэ termнn:',
		'Select_a_term' => 'Zvoliќ termнn',
		'Abridged_term' => 'Skrбtiќ termнn:',
		'Acronym' => 'Akronym',
		'Abbreviation' => 'Skratka',
		'Select_an_acronym' => 'Zvoliќ akronym alebo skratku',
		'Use_this_term' => 'Pouћiќ tento termнn:',
		'Use_this_term_explain' => 'Pripradiќ tento termнn k aktuбlne oznaиenйmu',
		'OK' => 'OK',
		'Delete' => 'Zmazaќ',
		'Cancel' => 'Zruљiќ',
	),
	'lt' => Array (
	),
	'is' => Array (
	),
	'hr' => Array (
	),
	'hu' => Array (
	),
	'gl' => Array (
	),
	'th' => Array (
	),
	'gr' => Array (
	),
	'hk' => Array (
	),
	'eu' => Array (
	),
	'bg' => Array (
	),
	'br' => Array (
		'Type_of_abridged_form' => 'Acrфnimo ou Abreviaзгo?',
		'Term_to_abridge' => 'Termo para abreviar',
		'Defined_term' => 'Acrфnimo ou Abreviaзгo Prй-definido',
		'Term' => 'Termo:',
		'Unabridged_term' => 'Termo Nгo-Abreviado:',
		'Select_a_term' => 'Selecione um termo:',
		'Abridged_term' => 'Termo Abreviado:',
		'Acronym' => 'Acrфnimo',
		'Abbreviation' => 'Abreviaзгo',
		'Select_an_acronym' => 'Selecione um acrфnimo ou abreviaзгo',
		'Use_this_term' => 'Use esse termo:',
		'Use_this_term_explain' => 'Associar esse termo а seleзгo',
		'OK' => 'OK',
		'Delete' => 'Excluir',
		'Cancel' => 'Cancelar',
	),
	'et' => Array (
	),
	'ar' => Array (
	),
	'he' => Array (
	),
	'ua' => Array (
	),
	'lv' => Array (
	),
	'jp' => Array (
	),
	'vn' => Array (
	),
	'ca' => Array (
	),
	'ba' => Array (
	),
	'kr' => Array (
	),
	'eo' => Array (
	),
	'my' => Array (
	),
	'hi' => Array (
	),
);
?>